import { ListCheck } from "lucide-react";
import { FieldMappingRow } from "~/components/atoms/FieldMappingRow";

interface Field {
	key: string;
	label: string;
	required?: boolean;
	description?: string;
	autoGenerated?: boolean;
}

interface ImportFieldMapperProps {
	fields: Field[];
	headers: string[];
	mappings: Record<string, string>;
	defaults: Record<string, string>;
	onMappingChange: (key: string, header: string | null) => void;
	onDefaultChange: (key: string, value: string | null) => void;
	fieldType: "required" | "system" | "optional";
	title: string;
	subtitle?: string;
	selectOptionsMap?: Record<string, Array<{ value: string; label: string }>>;
	resolveFieldSelectOptions?: (context: {
		fieldKey: string;
		previewHeaders: string[];
		previewData: string[][];
		columnMapping: Record<string, string>;
		baseOptions?: Array<{ value: string; label: string }>;
	}) => Array<{ value: string; label: string }> | undefined;
	previewHeaders?: string[];
	previewData?: string[][];
}

export function ImportFieldMapper({
	fields,
	headers,
	mappings,
	defaults,
	onMappingChange,
	onDefaultChange,
	fieldType,
	title,
	subtitle,
	selectOptionsMap = {},
	resolveFieldSelectOptions,
	previewHeaders = [],
	previewData = [],
}: ImportFieldMapperProps) {
	const autoMappedCount = Object.keys(mappings).filter(
		(key) => mappings[key] === key && !defaults[key],
	).length;

	const indicatorColor =
		fieldType === "required"
			? "bg-red-500"
			: fieldType === "system"
				? "bg-purple-500"
				: "bg-gray-300";

	return (
		<>
			{/* Section Header */}
			<div className="col-span-2 pt-2">
				{fieldType !== "optional" && (
					<div className="border bg-indigo-50/50 border-indigo-100 rounded-lg p-4 flex items-start gap-3 mb-4">
						<div className="p-2 bg-indigo-100 rounded-full text-indigo-600 mt-0.5 shadow-sm">
							<ListCheck className="w-4 h-4" />
						</div>
						<div>
							<h3 className="font-semibold text-sm mb-1 text-indigo-900">
								Map Columns
							</h3>
							<p className="text-xs text-indigo-700/80">
								Match your file's columns to the required system fields.
								{autoMappedCount > 0 && (
									<span className="font-medium ml-1 text-indigo-800">
										We found {autoMappedCount} auto-matches!
									</span>
								)}
							</p>
						</div>
					</div>
				)}

				<h4 className="flex items-center justify-between text-xs font-bold text-gray-900 uppercase tracking-wider mb-2 pb-2 border-b border-gray-100">
					<span className="flex items-center gap-2">
						<span
							className={`w-1.5 h-1.5 rounded-full ${indicatorColor} inline-block`}
						/>
						{title}
					</span>
					{subtitle && (
						<span className="text-[10px] font-normal normal-case bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full">
							{subtitle}
						</span>
					)}
				</h4>
			</div>

			{/* Field Mapping Rows */}
			{fields.map((field) => (
				<FieldMappingRow
					key={field.key}
					field={field}
					mapping={mappings[field.key]}
					defaultValue={defaults[field.key]}
					headers={headers}
					onMappingChange={onMappingChange}
					onDefaultChange={onDefaultChange}
					isRequired={field.required || fieldType === "required"}
					isSystem={fieldType === "system"}
					selectOptions={(() => {
						const resolved = resolveFieldSelectOptions?.({
							fieldKey: field.key,
							previewHeaders,
							previewData,
							columnMapping: mappings,
							baseOptions: selectOptionsMap[field.key],
						});
						return resolved ?? selectOptionsMap[field.key];
					})()}
				/>
			))}
		</>
	);
}
