import { useEffect, useMemo, useState } from "react";
import { Download, ChevronLeft, ChevronRight, PlusCircle } from "lucide-react";
import { Button } from "~/components/atoms/Button";
import { Checkbox } from "~/components/ui/checkbox";
import { Label } from "~/components/ui/label";
import { Input } from "~/components/ui/input";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "~/components/ui/select";
import { REQUIRED_FIELDS, OPTIONAL_FIELDS, SYSTEM_FIELDS } from "~/constants/import-fields";

export interface ImportField {
	key: string;
	label: string;
	required?: boolean;
	description?: string;
	aliases?: string[];
	autoGenerated?: boolean;
}

export interface EditableColumnConfig {
	type: "text" | "select";
	options?: { label: string; value: string }[];
	isLoadingOptions?: boolean;
	loadingOptionsLabel?: string;
	onOpen?: () => void;
	getOptions?: (context: {
		rowIndex: number;
		rowData: string[];
		previewData: string[][];
		previewHeaders: string[];
		columnMapping?: Record<string, string>;
	}) => { label: string; value: string }[];
}

export interface ImportPreviewValidationIssue {
	rowIndex: number;
	fieldKey: string;
	severity: "error" | "warning";
	value: string;
	message: string;
	createLabel?: string;
	createHref?: string;
}

export interface ImportPreviewValidationSummaryItem {
	fieldKey: string;
	severity: "error" | "warning";
	count: number;
	title: string;
	description: string;
	createLabel?: string;
	createHref?: string;
}

interface ImportPreviewTableProps {
	previewData: string[][];
	previewHeaders: string[];
	onDownloadMapped: () => void;
	showDownloadMapped?: boolean;
	autoCreateResources?: boolean;
	onAutoCreateChange?: (checked: boolean) => void;
	applyDefaultLeaveBalances?: boolean;
	onApplyDefaultLeaveBalancesChange?: (checked: boolean) => void;
	columnMapping?: Record<string, string>;
	defaultValues?: Record<string, string>;
	editableColumns?: Record<string, EditableColumnConfig>;
	onCellChange?: (rowIndex: number, colIndex: number, value: string, fieldKey?: string) => void;
	fields?: {
		required: ImportField[];
		optional: ImportField[];
		system?: ImportField[];
	};
	displayFields?: ImportField[];
	validationIssues?: ImportPreviewValidationIssue[];
	validationSummary?: ImportPreviewValidationSummaryItem[];
	validationMessage?: string;
}

type SelectOption = { label: string; value: string };
const CREATE_OPTION_PREFIX = "__create__:";

interface PreviewSelectCellProps {
	value: string;
	options: SelectOption[];
	isLoadingOptions?: boolean;
	loadingOptionsLabel?: string;
	validationIssue?: ImportPreviewValidationIssue;
	onOpen?: () => void;
	onChange: (value: string) => void;
}

function PreviewSelectCell({
	value,
	options,
	isLoadingOptions,
	loadingOptionsLabel,
	validationIssue,
	onOpen,
	onChange,
}: PreviewSelectCellProps) {
	const [isOpen, setIsOpen] = useState(false);
	const selectedLabel = useMemo(
		() => options.find((option) => option.value === value)?.label || value,
		[options, value],
	);

	return (
		<Select
			value={value}
			onOpenChange={(nextOpen) => {
				setIsOpen(nextOpen);
				if (nextOpen) {
					onOpen?.();
				}
			}}
			onValueChange={onChange}>
			<SelectTrigger
				className={`w-full text-xs h-8 ${
					validationIssue?.severity === "error"
						? "border-red-300 bg-red-50/30 focus:ring-red-200"
						: validationIssue?.severity === "warning"
							? "border-amber-300 bg-amber-50/30 focus:ring-amber-200"
							: ""
				}`}>
				<SelectValue placeholder="Select...">{selectedLabel}</SelectValue>
			</SelectTrigger>
			{isOpen && (
				<SelectContent>
					{isLoadingOptions && (
						<SelectItem value="__loading_options__" disabled>
							{loadingOptionsLabel || "Loading options..."}
						</SelectItem>
					)}
					{options.map((opt: SelectOption) => {
						const isCreateOption = opt.value.startsWith(CREATE_OPTION_PREFIX);
						return (
							<SelectItem
								key={opt.value}
								value={opt.value}
								className={
									isCreateOption
										? "text-emerald-700 focus:text-emerald-900"
										: undefined
								}>
								{isCreateOption ? (
									<span className="flex items-center gap-2 font-medium">
										<PlusCircle className="h-3.5 w-3.5 text-emerald-600" />
										<span>{opt.label}</span>
									</span>
								) : (
									opt.label
								)}
							</SelectItem>
						);
					})}
				</SelectContent>
			)}
		</Select>
	);
}

export function ImportPreviewTable({
	previewData,
	previewHeaders,
	onDownloadMapped,
	showDownloadMapped = true,
	autoCreateResources = false,
	onAutoCreateChange,
	applyDefaultLeaveBalances = false,
	onApplyDefaultLeaveBalancesChange,
	columnMapping,
	defaultValues,
	editableColumns,
	onCellChange,
	fields,
	displayFields,
	validationIssues = [],
	validationSummary = [],
	validationMessage,
}: ImportPreviewTableProps) {
	const [currentPage, setCurrentPage] = useState(1);
	const [activeIssueFilter, setActiveIssueFilter] = useState<string | null>(null);
	const rowsPerPage = 10;

	// Use provided fields or fall back to constants
	const allFields = useMemo(
		() =>
			displayFields ||
			(fields
				? [...fields.required, ...(fields.system || []), ...fields.optional]
				: [...REQUIRED_FIELDS, ...SYSTEM_FIELDS, ...OPTIONAL_FIELDS]),
		[displayFields, fields],
	);

	// Reorder columns based on field definition order so preview shows the
	// normalized import payload, not duplicate raw CSV columns.
	const { orderedColumnIndices, orderedDisplayHeaders, orderedFieldKeys } = useMemo(() => {
		const columnIndices: number[] = [];
		const displayHeaders: string[] = [];
		const fieldKeys: string[] = [];
		const headerIndexMap = new Map<string, number>();

		previewHeaders.forEach((header, index) => {
			headerIndexMap.set(header, index);
		});

		allFields.forEach((field) => {
			const mappedHeader = columnMapping?.[field.key];
			const headerToUse = mappedHeader || field.key;
			const columnIndex = headerIndexMap.get(headerToUse) ?? -1;

			columnIndices.push(columnIndex);
			displayHeaders.push(field.label);
			fieldKeys.push(field.key);
		});

		return {
			orderedColumnIndices: columnIndices,
			orderedDisplayHeaders: displayHeaders,
			orderedFieldKeys: fieldKeys,
		};
	}, [allFields, columnMapping, previewHeaders]);

	const validationIssueMap = useMemo(() => {
		const map = new Map<string, ImportPreviewValidationIssue>();
		validationIssues.forEach((issue) => {
			map.set(`${issue.rowIndex}:${issue.fieldKey}`, issue);
		});
		return map;
	}, [validationIssues]);

	const rowIssueMap = useMemo(() => {
		const map = new Map<number, Set<string>>();
		validationIssues.forEach((issue) => {
			const current = map.get(issue.rowIndex) || new Set<string>();
			current.add(issue.fieldKey);
			map.set(issue.rowIndex, current);
		});
		return map;
	}, [validationIssues]);

	const filteredPreviewRows = useMemo(() => {
		if (!activeIssueFilter) {
			return previewData;
		}

		return previewData
			.map((row, rowIndex) => ({
				row,
				rowIndex,
			}))
			.filter(({ rowIndex }) => rowIssueMap.get(rowIndex)?.has(activeIssueFilter));
	}, [activeIssueFilter, previewData, rowIssueMap]);

	const activeSummaryItem = activeIssueFilter
		? validationSummary.find((item) => item.fieldKey === activeIssueFilter) || null
		: null;
	const totalPages = Math.max(1, Math.ceil(filteredPreviewRows.length / rowsPerPage));
	const paginatedRows = useMemo(() => {
		const startIndex = (currentPage - 1) * rowsPerPage;
		if (!activeIssueFilter) {
			return previewData.slice(startIndex, startIndex + rowsPerPage).map((row, offset) => ({
				row,
				rowIndex: startIndex + offset,
			}));
		}

		return (filteredPreviewRows as Array<{ row: string[]; rowIndex: number }>).slice(
			startIndex,
			startIndex + rowsPerPage,
		);
	}, [activeIssueFilter, currentPage, filteredPreviewRows, previewData]);

	useEffect(() => {
		setCurrentPage(1);
	}, [activeIssueFilter]);

	useEffect(() => {
		if (!activeIssueFilter) return;
		if (activeSummaryItem && filteredPreviewRows.length > 0) return;
		setActiveIssueFilter(null);
	}, [activeIssueFilter, activeSummaryItem, filteredPreviewRows.length]);

	useEffect(() => {
		if (currentPage > totalPages) {
			setCurrentPage(totalPages);
		}
	}, [currentPage, totalPages]);

	return (
		<div className="space-y-4">
			{/* Preview Info */}
			<div className="flex justify-between items-center p-4 bg-orange-50 border border-orange-200 rounded-lg">
				<div>
					<h4 className="text-sm font-semibold text-orange-900 mb-1">Preview</h4>
					<p className="text-xs text-orange-700">
						Review your mapped data before importing. (Total rows: {previewData.length})
					</p>
					{validationMessage && (
						<p className="mt-2 text-xs font-medium text-red-700">{validationMessage}</p>
					)}
				</div>
			</div>

			{validationSummary.length > 0 && (
				<div className="space-y-2 rounded-xl border border-slate-200 bg-white p-3">
					<div className="flex items-center justify-between gap-3">
						<div className="flex items-center gap-3">
							<h4 className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
								Setup Gaps
							</h4>
							{activeSummaryItem && (
								<div className="flex items-center gap-2 rounded-full bg-slate-100 px-2.5 py-1">
									<span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
										Filter
									</span>
									<span className="text-[11px] font-medium text-slate-700">
										{activeSummaryItem.title}
									</span>
									<button
										type="button"
										onClick={() => setActiveIssueFilter(null)}
										className="text-[10px] font-medium text-slate-500 hover:text-slate-700">
										Clear
									</button>
								</div>
							)}
						</div>
						<span className="text-[11px] text-slate-500">
							{activeSummaryItem
								? `${filteredPreviewRows.length} row${filteredPreviewRows.length === 1 ? "" : "s"}`
								: `${validationSummary.length} type${validationSummary.length === 1 ? "" : "s"}`}
						</span>
					</div>
					<div className="overflow-x-auto pb-1">
						<div className="flex min-w-max items-stretch gap-2">
							{validationSummary.map((item) => {
								const isActive = activeIssueFilter === item.fieldKey;
								return (
									<button
										type="button"
										key={item.fieldKey}
										onClick={() =>
											setActiveIssueFilter((current) =>
												current === item.fieldKey ? null : item.fieldKey,
											)
										}
										className={`flex min-h-[84px] w-[198px] flex-col justify-between rounded-lg border px-3 py-2.5 text-left transition ${
											isActive
												? item.severity === "error"
													? "border-red-300 bg-red-50 shadow-sm ring-1 ring-red-200"
													: "border-amber-300 bg-amber-50 shadow-sm ring-1 ring-amber-200"
												: item.severity === "error"
													? "border-red-200 bg-red-50/50 hover:border-red-300 hover:bg-red-50/70"
													: "border-amber-200 bg-amber-50/50 hover:border-amber-300 hover:bg-amber-50/70"
										}`}>
										<div className="flex items-start justify-between gap-3">
											<div className="min-w-0">
												<p className="text-sm font-semibold leading-4 text-gray-900">
													{item.title}
												</p>
												<p className="mt-1 text-[10px] leading-4 text-gray-500">
													{item.count} row{item.count === 1 ? "" : "s"}
													{item.severity === "warning"
														? " use auto-create"
														: " need attention"}
												</p>
											</div>
											<span
												className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
													item.severity === "error"
														? "bg-red-100 text-red-700"
														: "bg-amber-100 text-amber-700"
												}`}>
												{item.count} row{item.count === 1 ? "" : "s"}
											</span>
										</div>
										<div className="mt-2 flex items-center justify-between gap-3">
											<span
												className={`text-[10px] font-medium ${
													isActive ? "text-gray-900" : "text-gray-500"
												}`}>
												{isActive ? "Filtered" : "Focus rows"}
											</span>
											{item.createHref && item.createLabel && (
												<a
													href={item.createHref}
													onClick={(event) => event.stopPropagation()}
													className="inline-flex text-[10px] font-medium text-orange-700 hover:text-orange-900">
													Create
												</a>
											)}
										</div>
									</button>
								);
							})}
						</div>
					</div>
				</div>
			)}

			{/* Preview Table */}
			<div className="border rounded-lg overflow-auto max-h-96">
				<table className="w-full text-sm">
					<thead className="bg-gray-50 border-b sticky top-0 z-10">
						<tr>
							{orderedDisplayHeaders.map((header, idx) => (
								<th
									key={idx}
									className="px-4 py-2 text-left text-xs font-semibold text-gray-700 whitespace-nowrap">
									{header}
								</th>
							))}
						</tr>
					</thead>
					<tbody className="divide-y">
						{paginatedRows.map(({ row, rowIndex: absoluteRowIdx }) => {
							return (
								<tr key={absoluteRowIdx} className="hover:bg-gray-50">
									{orderedColumnIndices.map((originalColIdx, displayColIdx) => {
										const fieldKey = orderedFieldKeys[displayColIdx];
										const cell =
											originalColIdx >= 0
												? row[originalColIdx] || ""
												: fieldKey
													? defaultValues?.[fieldKey] || ""
													: "";
										const editableConfig = fieldKey
											? editableColumns?.[fieldKey]
											: undefined;
										const resolvedOptions: SelectOption[] =
											editableConfig?.type === "select"
												? editableConfig.getOptions?.({
														rowIndex: absoluteRowIdx,
														rowData: row,
														previewData,
														previewHeaders,
														columnMapping,
													}) ||
													editableConfig.options ||
													[]
												: [];
										const normalizedCell = String(cell).trim();
										const selectOptions: SelectOption[] =
											editableConfig?.type === "select"
												? normalizedCell &&
													!resolvedOptions.some(
														(option: SelectOption) =>
															option.value === cell,
													)
													? [
															{
																value: cell,
																label: cell,
															},
															...resolvedOptions,
														]
													: resolvedOptions
												: [];
										const validationIssue = fieldKey
											? validationIssueMap.get(
													`${absoluteRowIdx}:${fieldKey}`,
												)
											: undefined;
										const createOption =
											validationIssue?.createHref &&
											validationIssue?.createLabel
												? {
														value: `${CREATE_OPTION_PREFIX}${validationIssue.createHref}`,
														label: validationIssue.createLabel,
													}
												: null;
										const dropdownOptions =
											editableConfig?.type === "select" && createOption
												? [...selectOptions, createOption]
												: selectOptions;
										const isLoadingOptions =
											editableConfig?.type === "select" &&
											editableConfig.isLoadingOptions;

										return (
											<td
												key={displayColIdx}
												className="px-4 py-2 text-xs text-gray-600 min-w-[150px] whitespace-nowrap align-top">
												{editableConfig ? (
													editableConfig.type === "select" ? (
														<div className="space-y-1">
															<PreviewSelectCell
																value={cell}
																options={dropdownOptions}
																isLoadingOptions={isLoadingOptions}
																loadingOptionsLabel={
																	editableConfig.loadingOptionsLabel
																}
																validationIssue={validationIssue}
																onOpen={editableConfig.onOpen}
																onChange={(val: string) => {
																	if (val === "__loading_options__") {
																		return;
																	}
																	if (
																		val.startsWith(
																			CREATE_OPTION_PREFIX,
																		)
																	) {
																		const href = val.slice(
																			CREATE_OPTION_PREFIX.length,
																		);
																		if (
																			typeof window !==
																				"undefined" &&
																			href
																		) {
																			window.location.href =
																				href;
																		}
																		return;
																	}
																	onCellChange?.(
																		absoluteRowIdx,
																		originalColIdx,
																		val,
																		fieldKey || undefined,
																	);
																}}
															/>
															<div className="min-h-[28px]">
																{validationIssue ? (
																	<p
																		className={`text-[10px] leading-4 ${
																			validationIssue.severity ===
																			"error"
																				? "text-red-600"
																				: "text-amber-700"
																		}`}>
																		{validationIssue.message}
																	</p>
																) : null}
															</div>
														</div>
													) : (
														<div className="space-y-1">
															<Input
																value={cell}
																onChange={(e) =>
																	onCellChange?.(
																		absoluteRowIdx,
																		originalColIdx,
																		e.target.value,
																		fieldKey || undefined,
																	)
																}
																className={`text-xs h-8 w-full ${
																	validationIssue?.severity ===
																	"error"
																		? "border-red-300 focus-visible:ring-red-200"
																		: validationIssue?.severity ===
																			  "warning"
																			? "border-amber-300 focus-visible:ring-amber-200"
																			: ""
																}`}
															/>
															<div className="min-h-[28px]">
																{validationIssue ? (
																	<p
																		className={`text-[10px] leading-4 ${
																			validationIssue.severity ===
																			"error"
																				? "text-red-600"
																				: "text-amber-700"
																		}`}>
																		{validationIssue.message}
																	</p>
																) : null}
															</div>
														</div>
													)
												) : (
													cell || "-"
												)}
											</td>
										);
									})}
								</tr>
							);
						})}
					</tbody>
				</table>
			</div>

			{/* Pagination Controls */}
			{filteredPreviewRows.length > rowsPerPage && (
				<div className="flex items-center justify-between border-t pt-4">
					<p className="text-xs text-gray-500">
						Showing {(currentPage - 1) * rowsPerPage + 1} to{" "}
						{Math.min(currentPage * rowsPerPage, filteredPreviewRows.length)} of{" "}
						{filteredPreviewRows.length} rows
					</p>
					<div className="flex items-center space-x-2">
						<Button
							variant="outline"
							size="sm"
							onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
							disabled={currentPage === 1}
							className="h-8 px-2 text-xs">
							<ChevronLeft className="h-4 w-4 mr-1" />
							Prev
						</Button>
						<span className="text-xs font-medium text-gray-700">
							Page {currentPage} of {totalPages}
						</span>
						<Button
							variant="outline"
							size="sm"
							onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
							disabled={currentPage >= totalPages}
							className="h-8 px-2 text-xs">
							Next
							<ChevronRight className="h-4 w-4 ml-1" />
						</Button>
					</div>
				</div>
			)}

			{/* Options */}
			<div className="space-y-3 mt-4">
				{onAutoCreateChange && (
					<div className="flex items-center space-x-2">
						<Checkbox
							id="autoCreate"
							checked={autoCreateResources}
							onCheckedChange={onAutoCreateChange}
						/>
						<Label
							htmlFor="autoCreate"
							className="text-sm text-gray-700 cursor-pointer">
							Automatically create missing departments, positions, and levels during
							import
						</Label>
					</div>
				)}

				{onApplyDefaultLeaveBalancesChange && (
					<div className="space-y-1">
						<div className="flex items-center space-x-2">
							<Checkbox
								id="applyDefaultLeaveBalances"
								checked={applyDefaultLeaveBalances}
								onCheckedChange={onApplyDefaultLeaveBalancesChange}
							/>
							<Label
								htmlFor="applyDefaultLeaveBalances"
								className="text-sm text-gray-700 cursor-pointer">
								Apply default leave balances
							</Label>
						</div>
						<p className="text-xs text-gray-500">
							Optional. When enabled, applies VACATION 15, SICK 10, and PERSONAL
							5 only when an employee has no leave balances.
						</p>
					</div>
				)}

				{showDownloadMapped && (
					<Button
						variant="outline"
						size="sm"
						onClick={onDownloadMapped}
						className="w-full gap-2">
						<Download className="h-4 w-4" />
						Download Mapped CSV
					</Button>
				)}
			</div>
		</div>
	);
}
