import type { Applicant } from "~/types/application";

export const MOCK_APPLICANTS: Applicant[] = [
	{
		id: "1",
		name: "Sarah Chen",
		email: "sarah.chen@email.com",
		position: "Senior Frontend Developer",
		status: "application_received",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2025-01-10"),
		lastUpdated: new Date("2025-01-10"),
	},
	{
		id: "2",
		name: "Marcus Johnson",
		email: "marcus.j@email.com",
		position: "Product Designer",
		status: "under_review",
		recruiter: "Jessica Lee",
		appliedDate: new Date("2025-01-08"),
		lastUpdated: new Date("2025-01-12"),
	},
	{
		id: "3",
		name: "Emily Rodriguez",
		email: "emily.r@email.com",
		position: "Senior Frontend Developer",
		status: "skill_check",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2025-01-05"),
		lastUpdated: new Date("2025-01-14"),
		skillCheckResult: "pending",
	},
	{
		id: "4",
		name: "David Kim",
		email: "david.kim@email.com",
		position: "Backend Engineer",
		status: "interview_stage",
		recruiter: "Michael Chen",
		appliedDate: new Date("2025-01-03"),
		lastUpdated: new Date("2025-01-15"),
		interviewRounds: 2,
	},
	{
		id: "5",
		name: "Priya Patel",
		email: "priya.p@email.com",
		position: "Full Stack Developer",
		status: "offer_extended",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2024-12-28"),
		lastUpdated: new Date("2025-01-16"),
		offerStatus: "pending",
	},
	{
		id: "6",
		name: "James Wilson",
		email: "james.w@email.com",
		position: "Product Designer",
		status: "rejected_closed",
		recruiter: "Jessica Lee",
		appliedDate: new Date("2025-01-01"),
		lastUpdated: new Date("2025-01-13"),
		rejectionReason: "Insufficient experience",
		rejectionFeedback: "Candidate has only 1 year of experience, position requires 3+",
	},
	{
		id: "7",
		name: "Lisa Anderson",
		email: "lisa.a@email.com",
		position: "Senior Frontend Developer",
		status: "hired",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2024-12-20"),
		lastUpdated: new Date("2025-01-15"),
	},
	{
		id: "8",
		name: "Ahmed Hassan",
		email: "ahmed.h@email.com",
		position: "Backend Engineer",
		status: "application_received",
		recruiter: "Michael Chen",
		appliedDate: new Date("2025-01-11"),
		lastUpdated: new Date("2025-01-11"),
	},
	{
		id: "9",
		name: "Rachel Green",
		email: "rachel.g@email.com",
		position: "Product Designer",
		status: "viewed",
		recruiter: "Jessica Lee",
		appliedDate: new Date("2025-01-09"),
		lastUpdated: new Date("2025-01-13"),
	},
	{
		id: "10",
		name: "Tom Bradley",
		email: "tom.b@email.com",
		position: "Full Stack Developer",
		status: "interview_stage",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2025-01-04"),
		lastUpdated: new Date("2025-01-15"),
		interviewRounds: 1,
	},
	{
		id: "11",
		name: "Nina Simmons",
		email: "nina.s@email.com",
		position: "Backend Engineer",
		status: "viewed",
		recruiter: "Michael Chen",
		appliedDate: new Date("2025-01-10"),
		lastUpdated: new Date("2025-01-12"),
	},
	{
		id: "12",
		name: "Sarah Chen",
		email: "sarah.chen@email.com",
		position: "Senior Frontend Developer",
		status: "application_received",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2025-01-10"),
		lastUpdated: new Date("2025-01-10"),
	},
	{
		id: "13",
		name: "Sarah Chen",
		email: "sarah.chen@email.com",
		position: "Senior Frontend Developer",
		status: "application_received",
		recruiter: "Alex Martinez",
		appliedDate: new Date("2025-01-10"),
		lastUpdated: new Date("2025-01-10"),
	},
];
