import type { Applicant } from "~/types/application";

const createApplicant = (
	id: string,
	name: string,
	email: string,
	position: string,
	status: Applicant["status"],
	recruiter: string,
	appliedDate: string,
	lastUpdated: string,
	extra: Partial<Applicant> = {},
): Applicant => {
	const [firstName, ...rest] = name.split(" ");
	const lastName = rest.join(" ") || firstName;

	return {
		id,
		firstName,
		lastName,
		name,
		email,
		position,
		status,
		recruiter,
		appliedDate: new Date(appliedDate),
		lastUpdated: new Date(lastUpdated),
		...extra,
	};
};

export const MOCK_APPLICANTS: Applicant[] = [
	createApplicant(
		"1",
		"Sarah Chen",
		"sarah.chen@email.com",
		"Senior Frontend Developer",
		"new",
		"Alex Martinez",
		"2025-01-10",
		"2025-01-10",
	),
	createApplicant(
		"2",
		"Marcus Johnson",
		"marcus.j@email.com",
		"Product Designer",
		"reviewing",
		"Jessica Lee",
		"2025-01-08",
		"2025-01-12",
	),
	createApplicant(
		"3",
		"Emily Rodriguez",
		"emily.r@email.com",
		"Senior Frontend Developer",
		"reviewing",
		"Alex Martinez",
		"2025-01-05",
		"2025-01-14",
		{ skillCheckResult: "pending" },
	),
	createApplicant(
		"4",
		"David Kim",
		"david.kim@email.com",
		"Backend Engineer",
		"interview",
		"Michael Chen",
		"2025-01-03",
		"2025-01-15",
		{ interviewRounds: 2 },
	),
	createApplicant(
		"5",
		"Priya Patel",
		"priya.p@email.com",
		"Full Stack Developer",
		"accepted",
		"Alex Martinez",
		"2024-12-28",
		"2025-01-16",
		{ offerStatus: "pending" },
	),
	createApplicant(
		"6",
		"James Wilson",
		"james.w@email.com",
		"Product Designer",
		"rejected",
		"Jessica Lee",
		"2025-01-01",
		"2025-01-13",
		{
			rejectionReason: "Insufficient experience",
			rejectionFeedback: "Candidate has only 1 year of experience, position requires 3+",
		},
	),
	createApplicant(
		"7",
		"Lisa Anderson",
		"lisa.a@email.com",
		"Senior Frontend Developer",
		"hired",
		"Alex Martinez",
		"2024-12-20",
		"2025-01-15",
	),
	createApplicant(
		"8",
		"Ahmed Hassan",
		"ahmed.h@email.com",
		"Backend Engineer",
		"new",
		"Michael Chen",
		"2025-01-11",
		"2025-01-11",
	),
	createApplicant(
		"9",
		"Rachel Green",
		"rachel.g@email.com",
		"Product Designer",
		"reviewing",
		"Jessica Lee",
		"2025-01-09",
		"2025-01-13",
	),
	createApplicant(
		"10",
		"Tom Bradley",
		"tom.b@email.com",
		"Full Stack Developer",
		"interview",
		"Alex Martinez",
		"2025-01-04",
		"2025-01-15",
		{ interviewRounds: 1 },
	),
	createApplicant(
		"11",
		"Nina Simmons",
		"nina.s@email.com",
		"Backend Engineer",
		"reviewing",
		"Michael Chen",
		"2025-01-10",
		"2025-01-12",
	),
	createApplicant(
		"12",
		"Sarah Chen",
		"sarah.chen@email.com",
		"Senior Frontend Developer",
		"new",
		"Alex Martinez",
		"2025-01-10",
		"2025-01-10",
	),
	createApplicant(
		"13",
		"Sarah Chen",
		"sarah.chen@email.com",
		"Senior Frontend Developer",
		"new",
		"Alex Martinez",
		"2025-01-10",
		"2025-01-10",
	),
];
