apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-truth-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bnpimanufacturingsolution/bandai-infra-bnpi-pats.git
    targetRevision: develop
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
