apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-truth-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ernestdodz/INFRA.git
    targetRevision: terraform-hyperv-clean-plan
    path: gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
