apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-truth-health
  labels:
    app: project-truth-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-truth-health
  template:
    metadata:
      labels:
        app: project-truth-health
    spec:
      containers:
        - name: project-truth-health
          image: project-truth-health:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: ENVIRONMENT
              value: LOCAL
            - name: APP_VERSION
              value: local
            - name: SERVICE_NAME
              value: project-truth
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
