apiVersion: v1
kind: ConfigMap
metadata:
  name: project-truth-environment
data:
  environment: prod
  release_tag: "f05da87e"
  runtime_image_tag: "develop"
  app_port: "3000"
  api_port: "3001"
  postgres_host_port: "15432"
  start_command: project-truth-bnpi-pats-env-start prod
  seed_command: project-truth-bnpi-pats-env-seed prod
