import { useCallback, useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Modal } from "~/components/atoms/Modal";
import { Button } from "~/components/atoms/Button";
import { ImportStepIndicator } from "~/components/atoms/ImportStepIndicator";
import { ImportUploadStep } from "~/components/molecules/employee/ImportUploadStep";
import { ImportFieldMapper } from "~/components/molecules/employee/ImportFieldMapper";
import { ImportPreviewTable } from "~/components/molecules/employee/ImportPreviewTable";
import type { EditableColumnConfig } from "~/components/molecules/employee/ImportPreviewTable";
import type {
	ImportPreviewValidationIssue,
	ImportPreviewValidationSummaryItem,
} from "~/components/molecules/employee/ImportPreviewTable";
import { ImportErrorDisplay } from "~/components/molecules/employee/ImportErrorDisplay";
import { InlineImportProgress } from "~/components/molecules/employee/InlineImportProgress";
import { Checkbox } from "~/components/ui/checkbox";
import { Label } from "~/components/ui/label";
import {
	parseCSVFile,
	autoMapHeaders,
	generateMappedCSV,
	generateFileFromData,
} from "~/lib/helpers/import.helpers";
import {
	cleanupExpiredSnapshots,
	deleteImportSnapshot,
	getImportSnapshot,
	setImportSnapshot,
	type ImportSnapshotEnvelope,
	type ImportStep,
	type PersistedFileMeta,
} from "~/lib/utils/import-persistence-idb";

export interface ImportField {
	key: string;
	label: string;
	required?: boolean;
	description?: string;
	aliases?: string[];
	autoGenerated?: boolean;
}

export interface ImportSelectOption {
	value: string;
	label: string;
}

export interface ResolveFieldSelectOptionsContext {
	fieldKey: string;
	previewHeaders: string[];
	previewData: string[][];
	columnMapping: Record<string, string>;
	baseOptions?: ImportSelectOption[];
}

export interface DerivePreviewRowValuesContext {
	rowIndex: number;
	changedFieldKey?: string;
	mappedRow: Record<string, string>;
	rawRow: Record<string, string>;
	previewHeaders: string[];
	columnMapping: Record<string, string>;
}

export interface PreviewValidationResult {
	issues: ImportPreviewValidationIssue[];
	summary: ImportPreviewValidationSummaryItem[];
	hasBlockingIssues: boolean;
	blockingMessage?: string;
}

export interface ImportFieldGroup {
	id: string;
	title: string;
	fieldType: "required" | "system" | "optional";
	fields: ImportField[];
	subtitle?: string;
}

interface GenericImportModalProps {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	persistenceKey?: string;
	title: string;
	description?: string;
	fields: {
		required: ImportField[];
		optional: ImportField[];
		system?: ImportField[];
	};
	fieldGroups?: ImportFieldGroup[];
	previewFields?: ImportField[];
	selectOptionsMap?: Record<string, Array<{ value: string; label: string }>>;
	resolveFieldSelectOptions?: (
		context: ResolveFieldSelectOptionsContext,
	) => ImportSelectOption[] | undefined;
	onDownloadTemplate: (count?: number) => void;
	onImport: (file: File, options?: any) => Promise<any> | void;
	isImporting?: boolean;
	showAutoCreateResources?: boolean;
	showApplyDefaultLeaveBalances?: boolean;
	showCreateTimesheets?: boolean;
	generateCustomField?: (name: string) => string;
	editableColumns?: Record<string, EditableColumnConfig>;
	customPreviewComponent?: React.ComponentType<any>;
	customPreviewProps?: Record<string, any>;
	importProgress?: {
		jobId: string;
		status: "processing" | "completed" | "failed";
		total: number;
		processed: number;
		success: number;
		failed: number;
		created?: number;
		updated?: number;
		skipped?: number;
		blocked?: number;
		errors?: Array<{ row: number; employeeId: string; error: string }>;
		warnings?: Array<{ row?: number; employeeId: string; stage: string; message: string }>;
		recentLog?: Array<{
			row: number;
			employeeId: string;
			fullName?: string;
			success: boolean;
			message?: string;
			createdAt?: string;
		}>;
		credentialExports?: Array<{
			row?: number;
			employeeId: string;
			fullName?: string;
			email: string;
			userName: string;
			password: string;
			role: string;
		}>;
		startedAt?: string;
		completedAt?: string;
		durationMs?: number;
	} | null;
	/** When true, show live activity log during import (e.g. employee import) */
	showLiveProgressLog?: boolean;
	autoDownloadMappedOnSuccess?: boolean;
	autoDownloadCredentialsOnSuccess?: boolean;
	showTemplateCount?: boolean;
	autoGenerateFields?: (context: {
		mappedRow: Record<string, string>;
		rawRow: Record<string, any>;
		rowIndex: number;
	}) => Record<string, string | undefined>;
	autoGeneratedFieldKeys?: string[];
	derivePreviewRowValues?: (
		context: DerivePreviewRowValuesContext,
	) => Record<string, string | undefined>;
	validatePreviewData?: (context: {
		previewHeaders: string[];
		previewData: string[][];
		columnMapping: Record<string, string>;
		autoCreateResources: boolean;
	}) => PreviewValidationResult;
	clientStateLoading?: boolean;
	clientStateLoadingLabel?: string;
	clientStateLoadingDetail?: string;
}

type InlineImportProgressState = NonNullable<GenericImportModalProps["importProgress"]>;

const IMPORT_STEP_PARAM_KEY = "importStep";
const LEGACY_STEP_PARAM_KEY = "step";
const IMPORT_SNAPSHOT_VERSION = 1;
const IMPORT_SNAPSHOT_TTL_MS = 24 * 60 * 60 * 1000;
const STEP_TO_PARAM_VALUE: Record<ImportStep, string> = {
	upload: "upload",
	map: "map",
	preview: "preview",
};

function waitForNextPaint(): Promise<void> {
	if (typeof window === "undefined") return Promise.resolve();
	return new Promise((resolve) => {
		window.requestAnimationFrame(() => {
			window.setTimeout(resolve, 0);
		});
	});
}

function parseImportStepParam(searchParams: URLSearchParams): ImportStep | null {
	const stepValue = searchParams.get(IMPORT_STEP_PARAM_KEY);

	if (stepValue === "1" || stepValue === "upload") return "upload";
	if (stepValue === "2" || stepValue === "map") return "map";
	if (stepValue === "3" || stepValue === "preview") return "preview";

	const legacyStepValue = searchParams.get(LEGACY_STEP_PARAM_KEY);
	if (legacyStepValue === "upload") return "upload";
	if (legacyStepValue === "map") return "map";
	if (legacyStepValue === "preview") return "preview";

	return null;
}

export function GenericImportModal({
	open,
	onOpenChange,
	persistenceKey,
	title,
	description,
	fields,
	fieldGroups,
	previewFields,
	selectOptionsMap = {},
	resolveFieldSelectOptions,
	onDownloadTemplate,
	onImport,
	isImporting = false,
	showAutoCreateResources = false,
	showApplyDefaultLeaveBalances = false,
	showCreateTimesheets = false,
	generateCustomField,
	editableColumns,
	customPreviewComponent: CustomPreviewComponent,
	customPreviewProps = {},
	importProgress,
	showLiveProgressLog = false,
	autoDownloadMappedOnSuccess = false,
	autoDownloadCredentialsOnSuccess = false,
	showTemplateCount = false,
	autoGenerateFields,
	autoGeneratedFieldKeys = [],
	derivePreviewRowValues,
	validatePreviewData,
	clientStateLoading = false,
	clientStateLoadingLabel = "Loading import setup...",
	clientStateLoadingDetail,
}: GenericImportModalProps) {
	const [importStep, setImportStep] = useState<ImportStep>("upload");
	const [importFile, setImportFile] = useState<File | null>(null);
	const [importError, setImportError] = useState<any>(null);
	const [autoCreateResources, setAutoCreateResources] = useState(false);
	const [applyDefaultLeaveBalances, setApplyDefaultLeaveBalances] = useState(false);
	const [createTimesheets, setCreateTimesheets] = useState(false);
	const [previewData, setPreviewData] = useState<string[][]>([]);
	const [previewHeaders, setPreviewHeaders] = useState<string[]>([]);
	const [columnMapping, setColumnMapping] = useState<Record<string, string>>({});
	const [defaultValues, setDefaultValues] = useState<Record<string, string>>({});
	const [isParsingFile, setIsParsingFile] = useState(false);
	const [isPreparingPreview, setIsPreparingPreview] = useState(false);
	const [isPreparingImportFile, setIsPreparingImportFile] = useState(false);
	const [filePrepareProgress, setFilePrepareProgress] = useState({ rows: 0, percent: 0 });
	const [localImportProgress, setLocalImportProgress] =
		useState<InlineImportProgressState | null>(null);
	const [preparedUploadStep, setPreparedUploadStep] = useState<ImportStep | null>(null);
	const [restoredFileMeta, setRestoredFileMeta] = useState<PersistedFileMeta | null>(null);
	const [isRestoreReady, setIsRestoreReady] = useState(false);
	const hasInitializedStepRef = useRef(false);
	const lastSyncedStepRef = useRef<ImportStep | null>(null);
	const suppressInitialStepCorrectionRef = useRef(false);
	const hasRestoredSessionRef = useRef(false);
	const downloadedMappedJobIdsRef = useRef<Set<string>>(new Set());
	const wasOpenRef = useRef(false);
	const previewDataForValidation = useDeferredValue(previewData);
	const previewHeadersForValidation = useDeferredValue(previewHeaders);
	const columnMappingForValidation = useDeferredValue(columnMapping);
	const autoCreateResourcesForValidation = useDeferredValue(autoCreateResources);

	const getCurrentSearchParams = useCallback(() => {
		if (typeof window === "undefined") {
			return new URLSearchParams();
		}
		return new URLSearchParams(window.location.search);
	}, []);

	const replaceUrlSearchParams = useCallback((mutator: (next: URLSearchParams) => void) => {
		if (typeof window === "undefined") return;
		const url = new URL(window.location.href);
		const next = new URLSearchParams(url.search);
		const before = next.toString();
		mutator(next);
		const after = next.toString();
		if (before === after) return;

		url.search = after ? `?${after}` : "";
		window.history.replaceState(window.history.state, "", url.toString());
	}, []);

	const getFileStep = useCallback((file: File | null): ImportStep | null => {
		if (!file) return null;
		const lowerName = file.name.toLowerCase();
		if (lowerName.endsWith(".csv")) return "map";
		if (lowerName.endsWith(".xlsx") || lowerName.endsWith(".xls")) return "preview";
		return "preview";
	}, []);

	const getEntityKey = useCallback(() => {
		const pathname = typeof window !== "undefined" ? window.location.pathname : "unknown-path";
		return persistenceKey?.trim() || `${pathname}::${title}`;
	}, [persistenceKey, title]);

	const clearPersistedSnapshot = useCallback(async () => {
		try {
			await deleteImportSnapshot(getEntityKey());
		} catch {
			// Ignore IndexedDB cleanup failures in UI flow
		}
	}, [getEntityKey]);

	const hasRestoredPreview =
		!importFile &&
		!!restoredFileMeta &&
		previewHeaders.length > 0 &&
		previewData.length > 0 &&
		!!preparedUploadStep;

	const canNavigateToStep = useCallback(
		(targetStep: ImportStep) => {
			if (targetStep === "upload") return true;
			if ((!importFile && !hasRestoredPreview) || !preparedUploadStep || isParsingFile) {
				return false;
			}
			if (targetStep === "map") return preparedUploadStep === "map";
			if (targetStep === "preview") return true;
			return false;
		},
		[hasRestoredPreview, importFile, isParsingFile, preparedUploadStep],
	);

	const goToStep = (targetStep: ImportStep) => {
		if (!canNavigateToStep(targetStep)) return;
		setImportError(null);
		if (targetStep === "preview" && preparedUploadStep === "map") {
			handleProceedToPreview();
			return;
		}
		setImportStep((currentStep) => (currentStep === targetStep ? currentStep : targetStep));
	};

	useEffect(() => {
		if (!open) return;

		let cancelled = false;

		const hydrate = async () => {
			try {
				await cleanupExpiredSnapshots(Date.now());
				const snapshot = await getImportSnapshot(getEntityKey());
				if (cancelled) return;

				if (!snapshot || typeof snapshot !== "object") {
					hasRestoredSessionRef.current = false;
					setIsRestoreReady(true);
					return;
				}

				const isExpired =
					typeof snapshot.savedAt !== "number" ||
					Date.now() - snapshot.savedAt >
						Number(snapshot.ttlMs || IMPORT_SNAPSHOT_TTL_MS);
				const isCsvSnapshot = String(snapshot.fileMeta?.name || "")
					.toLowerCase()
					.endsWith(".csv");
				const isInvalidStructure =
					!Array.isArray(snapshot.previewHeaders) ||
					!Array.isArray(snapshot.previewData) ||
					typeof snapshot.columnMapping !== "object" ||
					typeof snapshot.defaultValues !== "object";
				const isInvalidEntity =
					snapshot.version !== IMPORT_SNAPSHOT_VERSION ||
					snapshot.entityKey !== getEntityKey();

				if (isExpired || isInvalidEntity || !isCsvSnapshot || isInvalidStructure) {
					await clearPersistedSnapshot();
					if (cancelled) return;
					hasRestoredSessionRef.current = false;
					setIsRestoreReady(true);
					return;
				}

				const restoredPreparedStep = snapshot.preparedUploadStep || "map";
				const requestedStep = parseImportStepParam(getCurrentSearchParams());
				const restoredStep =
					requestedStep === "preview"
						? "preview"
						: requestedStep === "map" && restoredPreparedStep === "map"
							? "map"
							: requestedStep === "upload"
								? "upload"
								: snapshot.importStep || "map";

				setPreviewHeaders(snapshot.previewHeaders);
				setPreviewData(snapshot.previewData);
				setColumnMapping(snapshot.columnMapping || {});
				setDefaultValues(snapshot.defaultValues || {});
				setAutoCreateResources(Boolean(snapshot.autoCreateResources));
				setApplyDefaultLeaveBalances(Boolean(snapshot.applyDefaultLeaveBalances));
				setCreateTimesheets(Boolean(snapshot.createTimesheets));
				setPreparedUploadStep(restoredPreparedStep);
				setImportStep(restoredStep);
				setRestoredFileMeta(snapshot.fileMeta || null);
				setImportError(null);
				hasRestoredSessionRef.current = true;
				setIsRestoreReady(true);
			} catch {
				if (cancelled) return;
				hasRestoredSessionRef.current = false;
				setIsRestoreReady(true);
			}
		};

		hydrate();

		return () => {
			cancelled = true;
		};
	}, [clearPersistedSnapshot, getCurrentSearchParams, getEntityKey, open]);

	useEffect(() => {
		if (open) {
			wasOpenRef.current = true;
			if (!hasInitializedStepRef.current) {
				if (!isRestoreReady) return;

				if (hasRestoredSessionRef.current) {
					hasInitializedStepRef.current = true;
					lastSyncedStepRef.current = importStep;
					suppressInitialStepCorrectionRef.current = false;
					return;
				}

				const searchParams = getCurrentSearchParams();
				const stepFromUrl = parseImportStepParam(searchParams);
				const hasValidDeepLinkedStep =
					(stepFromUrl === "upload" ||
						stepFromUrl === "map" ||
						stepFromUrl === "preview") &&
					canNavigateToStep(stepFromUrl);
				const initialStep = hasValidDeepLinkedStep && stepFromUrl ? stepFromUrl : "upload";
				setImportStep(initialStep);
				hasInitializedStepRef.current = true;
				lastSyncedStepRef.current = initialStep;
				suppressInitialStepCorrectionRef.current = !!stepFromUrl && !hasValidDeepLinkedStep;
			}
			return;
		}

		if (!wasOpenRef.current) return;
		wasOpenRef.current = false;
		hasInitializedStepRef.current = false;
		lastSyncedStepRef.current = null;
		suppressInitialStepCorrectionRef.current = false;
		hasRestoredSessionRef.current = false;
		setIsRestoreReady(false);
		setImportFile(null);
		setImportError(null);
		setAutoCreateResources(false);
		setApplyDefaultLeaveBalances(showApplyDefaultLeaveBalances);
		setCreateTimesheets(false);
		setPreviewData([]);
		setPreviewHeaders([]);
		setColumnMapping({});
		setDefaultValues({});
		setLocalImportProgress(null);
		setImportStep("upload");
		setIsParsingFile(false);
		setIsPreparingPreview(false);
		setIsPreparingImportFile(false);
		setFilePrepareProgress({ rows: 0, percent: 0 });
		setPreparedUploadStep(null);
		setRestoredFileMeta(null);
		const searchParams = getCurrentSearchParams();
		if (
			searchParams.has(IMPORT_STEP_PARAM_KEY) ||
			searchParams.has("importAutoCreate") ||
			searchParams.has("importDefaultLeaveBalances") ||
			searchParams.has("importCreateTimesheets")
		) {
			replaceUrlSearchParams((next) => {
				next.delete(IMPORT_STEP_PARAM_KEY);
				next.delete("importAutoCreate");
				next.delete("importDefaultLeaveBalances");
				next.delete("importCreateTimesheets");
			});
		}
	}, [
		importStep,
		isRestoreReady,
		open,
		canNavigateToStep,
		getCurrentSearchParams,
		replaceUrlSearchParams,
		showApplyDefaultLeaveBalances,
	]);

	// Restore deep-linked auto-create state when opening modal.
	useEffect(() => {
		if (!open) return;
		if (showAutoCreateResources) {
			const autoCreateFromUrl = getCurrentSearchParams().get("importAutoCreate");
			if (autoCreateFromUrl === "true") {
				setAutoCreateResources(true);
			} else if (autoCreateFromUrl === "false") {
				setAutoCreateResources(false);
			}
		}
		if (showApplyDefaultLeaveBalances) {
			const leaveDefaultsFromUrl = getCurrentSearchParams().get("importDefaultLeaveBalances");
			if (leaveDefaultsFromUrl === "true") {
				setApplyDefaultLeaveBalances(true);
			} else if (leaveDefaultsFromUrl === "false") {
				setApplyDefaultLeaveBalances(false);
			} else {
				setApplyDefaultLeaveBalances(true);
			}
		}
		if (showCreateTimesheets) {
			const createTimesheetsFromUrl = getCurrentSearchParams().get("importCreateTimesheets");
			if (createTimesheetsFromUrl === "true") {
				setCreateTimesheets(true);
			} else if (createTimesheetsFromUrl === "false") {
				setCreateTimesheets(false);
			}
		}
	}, [
		open,
		showAutoCreateResources,
		showApplyDefaultLeaveBalances,
		showCreateTimesheets,
		getCurrentSearchParams,
	]);

	useEffect(() => {
		if (!open) return;
		if (!isRestoreReady) return;
		const stepFromUrl = parseImportStepParam(getCurrentSearchParams());
		if (
			suppressInitialStepCorrectionRef.current &&
			importStep === "upload" &&
			(stepFromUrl === "map" || stepFromUrl === "preview")
		) {
			return;
		}
		if (importStep === "upload" && !stepFromUrl) {
			lastSyncedStepRef.current = importStep;
			return;
		}
		if (lastSyncedStepRef.current === importStep && stepFromUrl === importStep) return;
		if (stepFromUrl !== importStep) {
			replaceUrlSearchParams((next) => {
				if (importStep === "upload") {
					next.delete(IMPORT_STEP_PARAM_KEY);
				} else {
					next.set(IMPORT_STEP_PARAM_KEY, STEP_TO_PARAM_VALUE[importStep]);
				}
			});
		}
		lastSyncedStepRef.current = importStep;
	}, [open, isRestoreReady, importStep, getCurrentSearchParams, replaceUrlSearchParams]);

	// Parse the selected file once so upload readiness and the deep-linked step stay aligned.
	useEffect(() => {
		if (!importFile) {
			if (!hasRestoredPreview) {
				setPreviewData([]);
				setPreviewHeaders([]);
				setColumnMapping({});
				setDefaultValues({});
				setPreparedUploadStep(null);
				setFilePrepareProgress({ rows: 0, percent: 0 });
				setImportStep((currentStep) => (currentStep === "upload" ? currentStep : "upload"));
			}
			return;
		}

		let isCancelled = false;
		setIsParsingFile(true);
		setFilePrepareProgress({ rows: 0, percent: 1 });
		setPreparedUploadStep(null);
		setImportError(null);

		if (getFileStep(importFile) === "map") {
			// Always parse all rows (-1) so we can paginate
			const limit = -1;
			parseCSVFile(importFile, limit, (progress) => {
				if (isCancelled) return;
				setFilePrepareProgress(progress);
			})
				.then(({ headers, previewData }) => {
					if (isCancelled) return;
					// Replace empty headers with safe placeholders to avoid SelectItem errors
					const safeHeaders = headers.map((h, i) => h.trim() || `Column ${i + 1}`);
					setPreviewHeaders(safeHeaders);
					setPreviewData(previewData);

					// Auto-map headers (use fields from closure)
					const allFields = [
						...fields.required,
						...(fields.system || []),
						...fields.optional,
					];
					const initialMapping = autoMapHeaders(safeHeaders, allFields);
					setColumnMapping(initialMapping);
					setPreparedUploadStep("map");
					setFilePrepareProgress({ rows: previewData.length, percent: 100 });

					// Move to mapping step
					setImportStep("map");
				})
				.catch((error) => {
					if (isCancelled) return;
					setImportError(error.message);
					toast.error("Failed to parse CSV file");
				})
				.finally(() => {
					if (isCancelled) return;
					setIsParsingFile(false);
				});
		} else {
			// For Excel files, skip mapping
			setPreviewData([]);
			setPreviewHeaders([]);
			setPreparedUploadStep("preview");
			setImportStep("preview");
			setFilePrepareProgress({ rows: 0, percent: 100 });
			setIsParsingFile(false);
		}

		return () => {
			isCancelled = true;
		};
	}, [
		fields.optional,
		fields.required,
		fields.system,
		getFileStep,
		hasRestoredPreview,
		importFile,
	]);

	useEffect(() => {
		if (!open) return;

		const hasPersistableData = previewHeaders.length > 0 && previewData.length > 0;
		if (!hasPersistableData) return;

		const effectiveFileMeta: PersistedFileMeta | undefined = importFile
			? {
					name: importFile.name,
					type: importFile.type || "text/csv",
					size: importFile.size || 0,
					lastModified: importFile.lastModified || Date.now(),
				}
			: restoredFileMeta || undefined;

		const isCsv = String(effectiveFileMeta?.name || "")
			.toLowerCase()
			.endsWith(".csv");
		if (!isCsv) return;

		const snapshot: ImportSnapshotEnvelope = {
			version: IMPORT_SNAPSHOT_VERSION,
			entityKey: getEntityKey(),
			savedAt: Date.now(),
			ttlMs: IMPORT_SNAPSHOT_TTL_MS,
			fileMeta: effectiveFileMeta,
			preparedUploadStep,
			importStep,
			previewHeaders,
			previewData,
			columnMapping,
			defaultValues,
			autoCreateResources,
			applyDefaultLeaveBalances,
			createTimesheets,
		};

		const timeoutId = window.setTimeout(() => {
			void setImportSnapshot(snapshot).catch(() => {
				// IndexedDB persistence is best-effort and should not block modal interactions.
			});
		}, 500);

		return () => window.clearTimeout(timeoutId);
	}, [
		applyDefaultLeaveBalances,
		autoCreateResources,
		columnMapping,
		createTimesheets,
		defaultValues,
		getEntityKey,
		importFile,
		importStep,
		open,
		preparedUploadStep,
		previewData,
		previewHeaders,
		restoredFileMeta,
	]);

	const handleFileSelect = (file: File) => {
		setImportFile(file);
		setRestoredFileMeta(null);
		setImportError(null);
		setLocalImportProgress(null);
		setPreparedUploadStep(null);
		suppressInitialStepCorrectionRef.current = false;
		clearPersistedSnapshot();
	};

	const handleMappingChange = (key: string, header: string | null) => {
		setColumnMapping((prev) => {
			if (header === null) {
				const next = { ...prev };
				delete next[key];
				return next;
			}
			return { ...prev, [key]: header };
		});
	};

	const handleDefaultChange = (key: string, value: string | null) => {
		setDefaultValues((prev) => {
			if (value === null) {
				const next = { ...prev };
				delete next[key];
				return next;
			}
			return { ...prev, [key]: value };
		});
	};

	const handleAutoCreateChange = (checked: boolean) => {
		const enabled = checked === true;
		setAutoCreateResources(enabled);
		if (open) {
			replaceUrlSearchParams((next) => {
				next.set("importAutoCreate", enabled ? "true" : "false");
			});
		}
	};

	const handleApplyDefaultLeaveBalancesChange = (checked: boolean) => {
		const enabled = checked === true;
		setApplyDefaultLeaveBalances(enabled);
		if (open) {
			replaceUrlSearchParams((next) => {
				next.set("importDefaultLeaveBalances", enabled ? "true" : "false");
			});
		}
	};

	const handleCreateTimesheetsChange = (checked: boolean) => {
		const enabled = checked === true;
		setCreateTimesheets(enabled);
		if (open) {
			replaceUrlSearchParams((next) => {
				next.set("importCreateTimesheets", enabled ? "true" : "false");
			});
		}
	};

	const ensureAllFieldColumnsInPreview = useCallback(() => {
		const allFieldKeys = [
			...fields.required.map((field) => field.key),
			...(fields.system || []).map((field) => field.key),
			...fields.optional.map((field) => field.key),
		];

		const nextHeaders = [...previewHeaders];
		let nextData = previewData.map((row) => [...row]);
		let changed = false;

		allFieldKeys.forEach((fieldKey) => {
			if (nextHeaders.includes(fieldKey)) return;
			changed = true;
			nextHeaders.push(fieldKey);
			const fallbackValue = defaultValues[fieldKey] ?? "";
			nextData = nextData.map((row) => [...row, fallbackValue]);
		});

		if (changed) {
			setPreviewHeaders(nextHeaders);
			setPreviewData(nextData);
		}
	}, [
		defaultValues,
		fields.optional,
		fields.required,
		fields.system,
		previewData,
		previewHeaders,
	]);

	const allFieldKeys = useMemo(
		() => [
			...fields.required.map((field) => field.key),
			...(fields.system || []).map((field) => field.key),
			...fields.optional.map((field) => field.key),
		],
		[fields.optional, fields.required, fields.system],
	);

	const applyPreviewDerivationToRow = useCallback(
		(
			rows: string[][],
			rowIndex: number,
			headers: string[],
			changedFieldKey?: string,
		): string[][] => {
			if (!derivePreviewRowValues) return rows;
			const row = rows[rowIndex];
			if (!row) return rows;

			const rawRow: Record<string, string> = {};
			headers.forEach((header, index) => {
				rawRow[header] = String(row[index] || "");
			});

			const mappedRow: Record<string, string> = {};
			allFieldKeys.forEach((fieldKey) => {
				const mappedHeader = columnMapping[fieldKey] || fieldKey;
				const mappedIndex = headers.indexOf(mappedHeader);
				mappedRow[fieldKey] = mappedIndex >= 0 ? String(row[mappedIndex] || "") : "";
			});

			const patch = derivePreviewRowValues({
				rowIndex,
				changedFieldKey,
				mappedRow,
				rawRow,
				previewHeaders: headers,
				columnMapping,
			});
			if (!patch || Object.keys(patch).length === 0) return rows;

			let nextRows = rows;
			let nextRow = row;
			let hasChange = false;

			Object.entries(patch).forEach(([fieldKey, derivedValue]) => {
				const value = String(derivedValue || "").trim();
				if (!value) return;

				const mappedHeader = columnMapping[fieldKey] || fieldKey;
				let targetIndex = headers.indexOf(mappedHeader);
				if (targetIndex < 0) {
					targetIndex = headers.indexOf(fieldKey);
				}
				if (targetIndex < 0) return;

				const currentValue = String(nextRow[targetIndex] || "").trim();
				const canOverwriteAutoGeneratedValue =
					Boolean(currentValue) &&
					Boolean(changedFieldKey) &&
					changedFieldKey !== fieldKey &&
					autoGeneratedFieldKeys.includes(fieldKey);
				if (currentValue && !canOverwriteAutoGeneratedValue) return;

				if (!hasChange) {
					nextRows = [...rows];
					nextRow = [...row];
					hasChange = true;
				}
				nextRow[targetIndex] = value;
			});

			if (!hasChange) return rows;
			nextRows[rowIndex] = nextRow;
			return nextRows;
		},
		[allFieldKeys, autoGeneratedFieldKeys, columnMapping, derivePreviewRowValues],
	);

	useEffect(() => {
		if (!open || importStep !== "preview") return;
		if (previewData.length === 0) return;
		ensureAllFieldColumnsInPreview();
	}, [ensureAllFieldColumnsInPreview, importStep, open, previewData.length]);

	useEffect(() => {
		if (!open || importStep !== "preview") return;
		if (previewData.length === 0) return;
		if (!derivePreviewRowValues) return;

		setPreviewData((prev) => {
			let working = prev;
			for (let i = 0; i < working.length; i++) {
				working = applyPreviewDerivationToRow(working, i, previewHeaders);
			}
			return working;
		});
	}, [
		applyPreviewDerivationToRow,
		derivePreviewRowValues,
		importStep,
		open,
		previewData.length,
		previewHeaders,
	]);

	const handleProceedToPreview = async () => {
		if (isPreparingPreview) return;
		setIsPreparingPreview(true);
		setFilePrepareProgress({ rows: previewData.length, percent: 1 });
		await waitForNextPaint();

		// Validate required fields
		const requiredFields = [
			...fields.required,
			...(fields.system || []).filter((field) => !field.autoGenerated),
		];
		const missingRequired = requiredFields.filter(
			(f) => !columnMapping[f.key] && defaultValues[f.key] === undefined,
		);

		if (missingRequired.length > 0) {
			setImportError(
				`Please map all required fields: ${missingRequired.map((f) => f.label).join(", ")}`,
			);
			setIsPreparingPreview(false);
			return;
		}

		ensureAllFieldColumnsInPreview();
		setFilePrepareProgress({ rows: previewData.length, percent: 100 });
		setImportStep("preview");
		setImportError(null);
		setIsPreparingPreview(false);
	};

	const getEffectiveColumnMapping = useCallback(() => {
		const nextMapping = { ...columnMapping };
		const knownFieldKeys = [
			...fields.required,
			...(fields.system || []),
			...fields.optional,
		].map((field) => field.key);

		knownFieldKeys.forEach((fieldKey) => {
			if (!nextMapping[fieldKey] && previewHeaders.includes(fieldKey)) {
				nextMapping[fieldKey] = fieldKey;
			}
		});

		return nextMapping;
	}, [columnMapping, fields.optional, fields.required, fields.system, previewHeaders]);

	const effectiveImportFileName = importFile?.name || restoredFileMeta?.name || "";
	const hasMappedTransform = useMemo(() => {
		if (!effectiveImportFileName) return false;
		if (!effectiveImportFileName.toLowerCase().endsWith(".csv")) return false;

		return (
			Object.keys(columnMapping).length > 0 ||
			Object.keys(defaultValues).length > 0 ||
			autoGeneratedFieldKeys.length > 0 ||
			(Boolean(editableColumns) && previewData.length > 0)
		);
	}, [
		autoGeneratedFieldKeys,
		columnMapping,
		defaultValues,
		editableColumns,
		effectiveImportFileName,
		previewData,
	]);

	const handleDownloadMapped = useCallback(async () => {
		if (!hasMappedTransform) return false;

		const effectiveImportFile =
			importFile ||
			(restoredFileMeta && previewHeaders.length > 0 && previewData.length > 0
				? generateFileFromData(previewHeaders, previewData, restoredFileMeta.name)
				: null);

		if (!effectiveImportFile) return false;

		const sourceFile =
			editableColumns && previewData.length > 0
				? generateFileFromData(previewHeaders, previewData, effectiveImportFile.name)
				: effectiveImportFile;
		const effectiveColumnMapping = getEffectiveColumnMapping();

		try {
			const mappedFile = await generateMappedCSV(
				sourceFile,
				effectiveColumnMapping,
				defaultValues,
				generateCustomField,
				autoGenerateFields,
				autoGeneratedFieldKeys,
			);
			const url = window.URL.createObjectURL(mappedFile);
			const a = document.createElement("a");
			a.href = url;
			a.download = `mapped_${effectiveImportFile.name}`;
			a.click();
			window.URL.revokeObjectURL(url);
			return true;
		} catch {
			toast.error("Failed to generate mapped CSV");
			return false;
		}
	}, [
		autoGenerateFields,
		autoGeneratedFieldKeys,
		defaultValues,
		editableColumns,
		generateCustomField,
		getEffectiveColumnMapping,
		hasMappedTransform,
		importFile,
		previewData,
		previewHeaders,
		restoredFileMeta,
	]);

	const handleCellChange = (
		rowIndex: number,
		colIndex: number,
		value: string,
		fieldKey?: string,
	) => {
		if (colIndex < 0 && fieldKey) {
			const existingIndex = previewHeaders.indexOf(fieldKey);
			const targetIndex = existingIndex >= 0 ? existingIndex : previewHeaders.length;

			if (existingIndex < 0) {
				const nextHeaders = [...previewHeaders, fieldKey];
				setPreviewHeaders(nextHeaders);
				setPreviewData((prev) => {
					const expanded = prev.map((row) => [...row, ""]);
					if (!expanded[rowIndex]) return expanded;
					expanded[rowIndex] = [...expanded[rowIndex]];
					expanded[rowIndex][targetIndex] = value;
					return applyPreviewDerivationToRow(expanded, rowIndex, nextHeaders, fieldKey);
				});
				return;
			}

			setPreviewData((prev) => {
				const newData = [...prev];
				if (!newData[rowIndex]) return newData;
				newData[rowIndex] = [...newData[rowIndex]];
				newData[rowIndex][targetIndex] = value;
				return applyPreviewDerivationToRow(newData, rowIndex, previewHeaders, fieldKey);
			});
			return;
		}

		setPreviewData((prev) => {
			const newData = [...prev];
			newData[rowIndex] = [...newData[rowIndex]];
			newData[rowIndex][colIndex] = value;
			return applyPreviewDerivationToRow(newData, rowIndex, previewHeaders, fieldKey);
		});
	};

	const handleImport = async () => {
		const effectiveImportFile =
			importFile ||
			(restoredFileMeta && previewHeaders.length > 0 && previewData.length > 0
				? generateFileFromData(previewHeaders, previewData, restoredFileMeta.name)
				: null);

		if (!effectiveImportFile) {
			setImportError("Please select a file to import");
			return;
		}

		setImportError(null);
		setLocalImportProgress(null);
		setIsPreparingImportFile(true);
		setFilePrepareProgress({ rows: previewData.length, percent: 1 });
		await waitForNextPaint();

		const previewValidation = validatePreviewData?.({
			previewHeaders,
			previewData,
			columnMapping,
			autoCreateResources,
		});
		if (previewValidation?.hasBlockingIssues) {
			setImportError(previewValidation.blockingMessage || "Please resolve preview issues.");
			setIsPreparingImportFile(false);
			return;
		}

		const hasMappings = Object.keys(columnMapping).length > 0;
		const hasDefaults = Object.keys(defaultValues).length > 0;
		let fileToImport = effectiveImportFile;

		// If user edited data, regenerate the file
		if (editableColumns && previewData.length > 0) {
			fileToImport = generateFileFromData(
				previewHeaders,
				previewData,
				effectiveImportFile.name,
			);
		}

		if (effectiveImportFile.name.endsWith(".csv") && (hasMappings || hasDefaults)) {
			const effectiveColumnMapping = getEffectiveColumnMapping();
			try {
				fileToImport = await generateMappedCSV(
					fileToImport,
					effectiveColumnMapping,
					defaultValues,
					generateCustomField,
					autoGenerateFields,
					autoGeneratedFieldKeys,
				);
			} catch (error) {
				setImportError("Failed to generate mapped CSV");
				toast.error("Failed to prepare import file");
				setIsPreparingImportFile(false);
				return;
			}
		}

		try {
			const importStartedAt = new Date();
			const result = await onImport(fileToImport, {
				autoCreate: autoCreateResources,
				applyDefaultLeaveBalances,
				createTimesheets,
			});
			const importCompletedAt = new Date();
			const data = result?.data || result;
			const envelope = data?.data || result?.data?.data;
			const summary =
				data?.summary ||
				envelope?.summary ||
				result?.summary ||
				result?.data?.summary ||
				result?.data?.data?.summary;
			const rawErrors = summary?.errors;
			const hasSummaryErrors = Array.isArray(rawErrors) && rawErrors.length > 0;
			const skippedCount = Number(summary?.skipped || 0);
			const failedCountFromSummary = Number(summary?.failed || 0);

			if (summary && (hasSummaryErrors || skippedCount > 0 || failedCountFromSummary > 0)) {
				const results = hasSummaryErrors
					? rawErrors.map((errorEntry: any, idx: number) => {
							const errorMessage =
								typeof errorEntry === "object" && errorEntry !== null
									? String(errorEntry.message || errorEntry.error || "")
									: String(errorEntry);
							const rowMatch = errorMessage.match(/^Row\s+([^:]+):\s*(.*)$/i);
							const rowLabel =
								String(errorEntry?.row || "").trim() ||
								rowMatch?.[1]?.trim() ||
								`${idx + 1}`;
							const message = rowMatch?.[2]?.trim() || errorMessage;
							return {
								row: idx + 1,
								success: false,
								employeeId: rowLabel,
								error: message,
							};
						})
					: [];

				setImportError({
					summary: {
						total:
							summary.total ||
							summary.totalRows ||
							(results.length > 0 ? results.length : skippedCount),
						totalRows: summary.totalRows || summary.total,
						success: Number(summary.created || 0) + Number(summary.updated || 0),
						failed: Math.max(
							failedCountFromSummary,
							Array.isArray(rawErrors) ? rawErrors.length : 0,
							skippedCount,
						),
						created: Number(summary.created || 0),
						updated: Number(summary.updated || 0),
					},
					results,
				});
				return;
			}

			// Handle structured errors (e.g. from bulk import API) - support both old and new formats
			if (
				(data?.summary?.failed && data.summary.failed > 0) ||
				(data?.summary?.skipped && data.summary.skipped > 0) ||
				(data?.summary?.errors && data.summary.errors.length > 0) ||
				(envelope?.summary?.failed && envelope.summary.failed > 0) ||
				(envelope?.summary?.skipped && envelope.summary.skipped > 0) ||
				(envelope?.summary?.errors && envelope.summary.errors.length > 0)
			) {
				setImportError(data?.summary ? data : envelope);
				return;
			}

			const importedCount =
				Number(summary?.created || 0) +
				Number(summary?.updated || 0) +
				Number(summary?.success || 0);
			const totalRows =
				Number(summary?.total || summary?.totalRows || 0) || previewData.length || 1;
			const successCount = importedCount > 0 ? importedCount : totalRows;
			setLocalImportProgress({
				jobId: `local-${Date.now()}`,
				status: "completed",
				total: totalRows,
				processed: totalRows,
				success: successCount,
				failed: 0,
				startedAt: importStartedAt.toISOString(),
				completedAt: importCompletedAt.toISOString(),
				durationMs: importCompletedAt.getTime() - importStartedAt.getTime(),
			});
			clearPersistedSnapshot();
		} catch (error: any) {
			setImportError(error.message || "Import failed");
		} finally {
			setIsPreparingImportFile(false);
		}
	};

	const steps = [
		{ id: "upload", label: "Upload File" },
		{ id: "map", label: "Map Fields" },
		{ id: "preview", label: "Review & Import" },
	];
	const isImportProcessing =
		isImporting ||
		isParsingFile ||
		isPreparingPreview ||
		isPreparingImportFile ||
		importProgress?.status === "processing";
	const isClientStateBusy = !isRestoreReady || clientStateLoading;
	const activeImportProgress = importProgress ?? localImportProgress;
	const effectiveFieldGroups = useMemo<ImportFieldGroup[]>(
		() =>
			fieldGroups || [
				{
					id: "required",
					title: "Required Fields",
					subtitle: "All must be mapped",
					fieldType: "required",
					fields: fields.required,
				},
				...(fields.system && fields.system.length > 0
					? [
							{
								id: "system",
								title: "System Configuration",
								subtitle: "Auto if blank",
								fieldType: "system" as const,
								fields: fields.system,
							},
						]
					: []),
				...(fields.optional && fields.optional.length > 0
					? [
							{
								id: "optional",
								title: "Optional Fields",
								fieldType: "optional" as const,
								fields: fields.optional,
							},
						]
					: []),
			],
		[fieldGroups, fields.optional, fields.required, fields.system],
	);
	const handleModalOpenChange = useCallback(
		(nextOpen: boolean) => {
			if (!nextOpen && isImportProcessing) return;
			onOpenChange(nextOpen);
		},
		[isImportProcessing, onOpenChange],
	);
	const isUploadReady =
		(Boolean(importFile) || hasRestoredPreview) && !!preparedUploadStep && !isParsingFile;
	const hasInlinePreviewError = importStep === "preview" && !!importError;
	const hasImportFailures =
		((activeImportProgress?.status === "completed" ||
			activeImportProgress?.status === "failed") &&
			((activeImportProgress?.failed ?? 0) > 0 ||
				(activeImportProgress?.errors?.length ?? 0) > 0)) ||
		hasInlinePreviewError;
	const showCloseOnly = !!activeImportProgress && activeImportProgress.status !== "processing";
	const previewValidation = useMemo(
		() =>
			validatePreviewData?.({
				previewHeaders: previewHeadersForValidation,
				previewData: previewDataForValidation,
				columnMapping: columnMappingForValidation,
				autoCreateResources: autoCreateResourcesForValidation,
			}) || null,
		[
			autoCreateResourcesForValidation,
			columnMappingForValidation,
			previewDataForValidation,
			previewHeadersForValidation,
			validatePreviewData,
		],
	);

	useEffect(() => {
		if (!autoDownloadMappedOnSuccess || !importProgress?.jobId) return;
		if (hasImportFailures || importProgress.status !== "completed" || !hasMappedTransform) {
			return;
		}
		if (downloadedMappedJobIdsRef.current.has(importProgress.jobId)) return;

		downloadedMappedJobIdsRef.current.add(importProgress.jobId);
		void handleDownloadMapped();
	}, [
		autoDownloadMappedOnSuccess,
		handleDownloadMapped,
		hasImportFailures,
		hasMappedTransform,
		importProgress,
	]);

	return (
		<Modal
			open={open}
			onOpenChange={handleModalOpenChange}
			title={title}
			description={
				description === undefined
					? "Upload a CSV/Excel file to bulk import data"
					: description
			}
			className="max-w-4xl">
			<div className="space-y-6">
				{/* Step Indicator */}
				<ImportStepIndicator
					steps={steps}
					currentStep={importStep}
					onStepClick={(stepId) => goToStep(stepId as ImportStep)}
					canClickStep={(stepId) => canNavigateToStep(stepId as ImportStep)}
				/>

				{(!isRestoreReady || clientStateLoading) && (
					<div className="space-y-2">
						<InlineImportProgress
							progress={null}
							isLoading
							loadingLabel={
								!isRestoreReady
									? "Restoring saved import preview..."
									: clientStateLoadingLabel
							}
						/>
						{clientStateLoadingDetail && isRestoreReady && (
							<p className="text-xs text-gray-500">{clientStateLoadingDetail}</p>
						)}
					</div>
				)}

				{/* Error Display */}
				{importError && importStep !== "preview" && (
					<ImportErrorDisplay
						error={importError}
						onDismiss={() => setImportError(null)}
					/>
				)}

				{/* Step Content */}
				{isRestoreReady && importStep === "upload" && (
					<ImportUploadStep
						onFileSelect={handleFileSelect}
						onDownloadTemplate={onDownloadTemplate}
						selectedFile={importFile}
						requiredFields={fields.required.map((field) => field.label)}
						importEntityLabel={title.replace(/^Import\s+/i, "")}
						showTemplateCount={showTemplateCount}
						isPreparingFile={isParsingFile}
						prepareProgress={filePrepareProgress}
					/>
				)}

				{isRestoreReady &&
					importStep === "map" &&
					(isPreparingPreview ? (
						<InlineImportProgress
							progress={null}
							isLoading
							loadingLabel="Preparing preview rows..."
						/>
					) : (
						<div className="grid grid-cols-2 gap-x-6 gap-y-4 max-h-[55vh] overflow-y-auto pr-2 custom-scrollbar p-1">
							{effectiveFieldGroups.map((group) => (
								<ImportFieldMapper
									key={group.id}
									fields={group.fields}
									headers={previewHeaders}
									previewHeaders={previewHeaders}
									previewData={previewData}
									mappings={columnMapping}
									defaults={defaultValues}
									onMappingChange={handleMappingChange}
									onDefaultChange={handleDefaultChange}
									fieldType={group.fieldType}
									title={group.title}
									subtitle={group.subtitle}
									selectOptionsMap={selectOptionsMap}
									resolveFieldSelectOptions={resolveFieldSelectOptions}
								/>
							))}
						</div>
					))}

				{isRestoreReady && importStep === "preview" && (
					<div className="space-y-4">
						{showCreateTimesheets && (
							<div className="rounded-lg border border-gray-200 bg-gray-50 px-4 py-3">
								<div className="flex items-start space-x-3">
									<Checkbox
										id="createTimesheetsPreview"
										checked={createTimesheets}
										disabled={isImportProcessing}
										onCheckedChange={handleCreateTimesheetsChange}
										className="mt-0.5"
									/>
									<div className="space-y-1">
										<Label
											htmlFor="createTimesheetsPreview"
											className="text-sm font-medium text-gray-800 cursor-pointer">
											Create timesheets for imported attendance
										</Label>
										<p className="text-xs text-muted-foreground">
											Creates missing approved timesheets for payroll periods
											touched by the imported attendance rows. Existing
											timesheets stay unchanged.
										</p>
									</div>
								</div>
							</div>
						)}
						{/* Show progress as soon as import starts (jobId + polling), so user sees bar and % live */}
						{/* Once import starts, hide preview table and show only progress */}
						{activeImportProgress || isImporting || isPreparingImportFile ? (
							<div className="space-y-3">
								<InlineImportProgress
									progress={activeImportProgress ?? null}
									isLoading={
										(isImporting || isPreparingImportFile) &&
										!activeImportProgress
									}
									loadingLabel={
										isPreparingImportFile
											? "Preparing import file locally..."
											: "Starting import..."
									}
									showLiveLog={showLiveProgressLog}
									autoDownloadCredentialsOnSuccess={
										autoDownloadCredentialsOnSuccess
									}
								/>
								{showAutoCreateResources && (
									<div className="space-y-2">
										<div className="flex items-center space-x-2">
											<Checkbox
												id="autoCreatePreview"
												checked={autoCreateResources}
												disabled={isImportProcessing}
												onCheckedChange={(checked) =>
													setAutoCreateResources(checked === true)
												}
											/>
											<Label
												htmlFor="autoCreatePreview"
												className="text-sm text-gray-700 cursor-pointer">
												Automatically create missing departments, positions,
												and levels during import
											</Label>
										</div>
										<p className="text-xs text-muted-foreground">
											Status:{" "}
											<span className="font-medium text-foreground">
												{autoCreateResources ? "Enabled" : "Disabled"}
											</span>
											. Missing schedules must be selected or created from
											Schedule setup.
										</p>
									</div>
								)}
								{showApplyDefaultLeaveBalances && (
									<div className="space-y-2">
										<div className="flex items-center space-x-2">
											<Checkbox
												id="defaultLeaveBalancesPreview"
												checked={applyDefaultLeaveBalances}
												disabled={isImportProcessing}
												onCheckedChange={
													handleApplyDefaultLeaveBalancesChange
												}
											/>
											<Label
												htmlFor="defaultLeaveBalancesPreview"
												className="text-sm text-gray-700 cursor-pointer">
												Apply default leave balances
											</Label>
										</div>
										<p className="text-xs text-muted-foreground">
											Optional. When enabled, applies VACATION 15, SICK 10,
											and PERSONAL 5 only when an employee has no leave
											balances. Status:{" "}
											<span className="font-medium text-foreground">
												{applyDefaultLeaveBalances ? "Enabled" : "Disabled"}
											</span>
										</p>
									</div>
								)}
							</div>
						) : (
							<>
								{CustomPreviewComponent ? (
									<CustomPreviewComponent
										data={previewData.map((row) => {
											const obj: Record<string, any> = {};
											previewHeaders.forEach((header, index) => {
												obj[header] = row[index] || "";
											});
											return obj;
										})}
										onChange={(updatedData: Record<string, any>[]) => {
											// Convert updated data back to previewData format
											const newPreviewData = updatedData.map(
												(obj: Record<string, any>) =>
													previewHeaders.map(
														(header) => obj[header] || "",
													),
											);
											setPreviewData(newPreviewData);
										}}
										{...customPreviewProps}
									/>
								) : (
									<ImportPreviewTable
										previewData={previewData}
										previewHeaders={previewHeaders}
										onDownloadMapped={handleDownloadMapped}
										showDownloadMapped={hasMappedTransform}
										autoCreateResources={autoCreateResources}
										onAutoCreateChange={
											showAutoCreateResources
												? handleAutoCreateChange
												: undefined
										}
										applyDefaultLeaveBalances={applyDefaultLeaveBalances}
										onApplyDefaultLeaveBalancesChange={
											showApplyDefaultLeaveBalances
												? handleApplyDefaultLeaveBalancesChange
												: undefined
										}
										columnMapping={columnMapping}
										defaultValues={defaultValues}
										editableColumns={editableColumns}
										onCellChange={
											editableColumns ? handleCellChange : undefined
										}
										fields={fields}
										validationIssues={previewValidation?.issues}
										validationSummary={previewValidation?.summary}
										validationMessage={previewValidation?.blockingMessage}
										displayFields={previewFields}
									/>
								)}
							</>
						)}
						{importError && (
							<ImportErrorDisplay
								error={importError}
								onDismiss={() => setImportError(null)}
							/>
						)}
					</div>
				)}

				{/* Footer Actions */}
				<div className="flex justify-between pt-4 border-t">
					<Button
						type="button"
						variant="outline"
						disabled={isImportProcessing}
						onClick={() => {
							if (importStep === "map") {
								setLocalImportProgress(null);
								setImportStep("upload");
							} else if (importStep === "preview") {
								setLocalImportProgress(null);
								setImportStep(preparedUploadStep === "map" ? "map" : "upload");
							} else {
								handleModalOpenChange(false);
							}
						}}>
						{importStep === "upload" ? "Cancel" : "Back"}
					</Button>

					{showCloseOnly ? (
						<Button type="button" onClick={() => handleModalOpenChange(false)}>
							Close
						</Button>
					) : (
						<Button
							type="button"
							onClick={() => {
								if (importStep === "upload") {
									if (!isUploadReady || !preparedUploadStep) {
										setImportError(
											importFile || hasRestoredPreview
												? "Please wait for the selected file to finish preparing."
												: "Please select a file.",
										);
										return;
									}
									setImportStep(preparedUploadStep);
								} else if (importStep === "map") {
									handleProceedToPreview();
								} else {
									handleImport();
								}
							}}
							disabled={
								(importStep === "upload" &&
									(!isUploadReady || isClientStateBusy)) ||
								(importStep !== "upload" &&
									(isImportProcessing || isClientStateBusy))
							}>
							{importStep === "preview"
								? isImportProcessing
									? "Importing..."
									: hasImportFailures
										? "Retry Import"
										: "Import Data"
								: isPreparingPreview
									? "Preparing..."
									: "Next"}
						</Button>
					)}
				</div>
			</div>
		</Modal>
	);
}
