namespace: prod

resources:
  - priority-classes.yaml
  - runtime.yaml

images:
  - name: bnpi-pats-api-db-init
    newTag: develop
  - name: bnpi-pats-api-local
    newTag: develop
  - name: bnpi-pats-app-local
    newTag: develop
