apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-truth-health
spec:
  template:
    spec:
      containers:
        - name: project-truth-health
          image: project-truth-health:uat
          env:
            - name: ENVIRONMENT
              value: UAT
            - name: APP_VERSION
              value: uat
            - name: SERVICE_NAME
              value: project-truth
