import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const readAppFile = (path: string) => readFileSync(join(process.cwd(), path), "utf8");

describe("admin device user and log sync UI contract", () => {
	it("keeps device user sync separate from device log sync", () => {
		const manage = readAppFile("app/routes/admin/devices/manage.tsx");
		const enroll = readAppFile("app/routes/admin/devices/enroll.tsx");
		const events = readAppFile("app/routes/admin/devices/events.tsx");
		const deviceHooks = readAppFile("app/lib/hooks/useDevices.ts");

		expect(enroll).toContain("Merge users");
		expect(manage).toContain("Sync Center");
		expect(manage).toContain("View Device Users");
		expect(manage).toContain("View Device Events");
		expect(enroll).toContain('title="Merge device users"');
		expect(manage).toContain('data-field-path="config.vendor"');
		expect(manage).toContain("Device vendor");
		expect(manage).toContain("HRIS applies the correct runtime settings automatically.");
		expect(manage).toContain('data-field-path="config.employeeKioskLoginEnabled"');
		expect(manage).toContain("Enable biometric kiosk login");
		expect(manage).toContain("sign in the employee kiosk automatically");
		expect(manage).not.toContain('data-field-path="config.source"');
		expect(manage).not.toContain('data-field-path="config.sdkPort"');
		expect(manage).not.toContain('data-field-path="config.webhookPath"');
		expect(manage).not.toContain("Runtime adapter *");
		expect(manage).not.toContain("Callback path");
		expect(manage).not.toContain("Internal adapter key");
		expect(manage).toContain('next.set("action", "sync-review")');
		expect(manage).toContain('next.set("action", "device-users")');
		expect(manage).not.toContain("enroll-users");
		expect(enroll).toContain("Overview");
		expect(enroll).toContain("<Tabs");
		expect(enroll).toContain("Device Users");
		expect(enroll).toContain("<span>Device</span>");
		expect(enroll).toContain("<span>Address</span>");
		expect(enroll).toContain("<span>Status</span>");
		expect(enroll).toContain("<span>Source users</span>");
		expect(enroll).toContain("<span>HRIS users</span>");
		expect(enroll).toContain("From device");
		expect(enroll).toContain("Gap");
		expect(enroll).toContain("Needs match");
		expect(enroll).toContain("Saved in HRIS");
		expect(enroll).toContain("Needs link");
		expect(enroll).toContain("source");
		expect(enroll).toContain("saved");
		expect(enroll).toContain("Listener");
		expect(enroll).toContain("Open");
		expect(enroll).toContain("<span>Last sync</span>");
		expect(enroll).toContain("Actions</span>");
		expect(enroll).toContain("xl:grid-cols-[minmax(190px,1.45fr)_124px_128px_150px_156px_112px_96px]");
		expect(enroll).toContain("whitespace-normal break-words");
		expect(enroll).toContain("openPhysicalDeviceUsers");
		expect(enroll).toContain("Choose a device first");
		expect(enroll).toContain("Back to device summary");
		expect(enroll).toContain("Refresh summary");
		expect(enroll).toContain("Recent saved activity");
		expect(enroll).toContain("Shows callback, reconcile, and backfill rows saved for this");
		expect(enroll).toContain("device.");
		expect(enroll).toContain("Refresh activity");
		expect(enroll).toContain("formatActivityOrigin");
		expect(enroll).toContain("formatActivityDetail");
		expect(enroll).toContain("rawSdkPersistence");
		expect(enroll).toContain("useDeviceActivity");
		expect(enroll).toContain("Device-user sync");
		expect(enroll).toContain("Review user sync");
		expect(enroll).not.toContain("Sync first");
		expect(enroll).toContain("Change employee link");
		expect(enroll).toContain("Link employee");
		expect(enroll).toContain("Save and link");
		expect(enroll).toContain("Submitting will save current");
		expect(enroll).toContain("device users first, then link the employee");
		expect(enroll).toContain("deviceService.getDeviceUsers");
		expect(enroll).toContain("vendorUserId: linkTarget.vendorUserId");
		expect(enroll).toContain("vendorUserIds");
		expect(enroll).toContain("linkTarget.hrisDeviceUser || null");
		expect(enroll).toContain('status: "UNMATCHED"');
		expect(enroll).toContain("openDbDeviceUsers?.deviceUsers");
		expect(enroll).toContain("mergedDeviceUserRows.length === 0");
		expect(enroll).toContain("CHECKING_LINK");
		expect(enroll).toContain("Checking HRIS link");
		expect(enroll).toContain("LINK_CHECK_FAILED");
		expect(enroll).toContain("Could not verify link");
		expect(enroll).toContain("Search employee name, ID, device ID");
		expect(enroll).toContain("Unlink employee");
		expect(enroll).toContain('title="Unlink employee"');
		expect(enroll).toContain("Confirm this device user should be unlinked");
		expect(enroll).toContain("Device Logs");
		expect(enroll).toContain("Sync Runs");
		expect(enroll).toContain("Review log sync");
		expect(enroll).toContain("Review sync");
		expect(enroll).toContain("fingerprintTemplate");
		expect(enroll).toContain("faceTemplate");
		expect(enroll).toContain("missing biometric custody in the background");
		expect(enroll).toContain("deviceIds: [selectedDeviceId]");
		expect(enroll).toContain("You can close this window and reopen status");
		expect(enroll).toContain('["Captured", effectiveDeviceUserSyncJobProgress?.biometricCaptured');
		expect(enroll).toContain('["Failed", effectiveDeviceUserSyncJobProgress?.biometricFailed');
		expect(enroll).toContain("Device-user sync status");
		expect(enroll).toContain("Open device-user sync status");
		expect(enroll).toContain("biometric credentials");
		expect(enroll).toContain("Current credential");
		expect(enroll).toContain("Already present");
		expect(enroll).toContain("Encrypted custody only");
		expect(enroll).toContain("deviceUserSyncStatusBubble");
		expect(enroll).toContain("Merge users");
		expect(enroll).toContain('title="Merge device users"');
		expect(enroll).toContain("Checking which Hikvision devices are available (up to 5 seconds).");
		expect(enroll).toContain("offline or unavailable skipped");
		expect(enroll).toContain("Merge needs at least two available devices.");
		expect(enroll).toContain("typeof preview.vendorUserCount === \"number\"");
		expect(enroll).toContain("Preview merge by unique ID");
		expect(enroll).toContain("Preview recommended choices");
		expect(enroll).toContain("selected unique ID");
		expect(enroll).toContain("selected potential write");
		expect(enroll).toContain("Deselect all");
		expect(enroll).toContain("selectedUserKeys");
		expect(enroll).toContain("mergeCredentialTruth");
		expect(enroll).toContain("Issue: ${mergePlural(issueCount, \"device\")}");
		expect(enroll).toContain("Expected active devices");
		expect(enroll).toContain("Unique IDs");
		expect(enroll).toContain("Device records read");
		expect(enroll).toContain("Issue details");
		expect(enroll).toContain("SdkMergeListMode");
		expect(enroll).toContain("sdkMergeUniqueRows");
		expect(enroll).toContain("sdkMergeRecordRows");
		expect(enroll).toContain("sdkMergeWriteRows");
		expect(enroll).toContain("setSdkMergeListMode");
		expect(enroll).toContain("setSdkMergeDeviceListMode");
		expect(enroll).toContain("Linked record");
		expect(enroll).toContain("Connected");
		expect(enroll).toContain("Missing");
		expect(enroll).toContain("SdkMergeSourceReviewState");
		expect(enroll).toContain("selectedSdkMergeSourceReviewRow");
		expect(enroll).toContain("Compare the current device truth against available source records.");
		expect(enroll).toContain("Current");
		expect(enroll).toContain("Recommended");
		expect(enroll).toContain("Available for review");
		expect(enroll).toContain("Per-device impact");
		expect(enroll).toContain("IDs read");
		expect(enroll).toContain("sdkMergeRowMatchesDevice");
		expect(enroll).toContain("row.targetDeviceId === deviceId");
		expect(enroll).toContain("Showing");
		expect(enroll).toContain("Page {safeSdkMergePage} of {sdkMergeTotalPages}");
		expect(enroll).toContain("Preview mode is on.");
		expect(enroll).toContain("<span>Fingerprint</span>");
		expect(enroll).toContain("<span>Face</span>");
		expect(enroll).toContain("<span>Card</span>");
		expect(enroll).toContain("SdkMergeCredentialPickerState");
		expect(enroll).toContain("Credential source");
		expect(enroll).toContain("Choose which device should supply this credential.");
		expect(enroll).toContain("truth.present");
		expect(enroll).toContain("truth.expected");
		expect(enroll).toContain("truth.connectedDevices");
		expect(enroll).toContain("truth.missingDevices");
		expect(enroll).toContain("CheckCircle2");
		expect(enroll).toContain("Review sources");
		expect(enroll).not.toContain("Hide details");
		expect(enroll).not.toContain("Source comparison");
		expect(enroll).not.toContain("Finger / Face / Card");
		expect(enroll).not.toContain("Dry-run only for now");
		expect(enroll).not.toContain("dry-run mode prevents writes");
		expect(enroll).not.toContain("Dry run is on.");
		expect(enroll).toContain("Potential writes");
		expect(enroll).toContain("Keep");
		expect(enroll).toContain("Clear");
		expect(enroll).toContain("configuredDeviceIds.length < 2");
		expect(enroll).toContain("sdkMergeBlockingCount");
		expect(enroll).toContain("Read from device");
		expect(enroll).toContain("Current view");
		expect(enroll).toContain("HRIS records");
		expect(enroll).toContain("Linked employees");
		expect(enroll).toContain("Needs link");
		expect(enroll).toContain("SOURCE_ONLY");
		expect(enroll).toContain("Refresh source users");
		expect(enroll).toContain('aria-label="Export device users"');
		expect(enroll).toContain('aria-label="Import device users"');
		expect(enroll).toContain("Export device users");
		expect(enroll).toContain("Import device users");
		expect(enroll).toContain("Current page");
		expect(enroll).toContain("Current filter");
		expect(enroll).toContain("Selected rows");
		expect(enroll).toContain("All device users");
		expect(enroll).toContain("deviceUserExportScopeLabel");
		expect(enroll).toContain("deviceUserExportScopeCount");
		expect(enroll).toContain("DeviceUserExportFormat");
		expect(enroll).toContain("CSV");
		expect(enroll).toContain("Excel");
		expect(enroll).toContain("Package JSON");
		expect(enroll).toContain("Spreadsheet custody rows");
		expect(enroll).toContain("Native Excel .xlsx workbook");
		expect(enroll).toContain("XLSX.utils.json_to_sheet");
		expect(enroll).toContain("downloadDeviceUserExport");
		expect(enroll).toContain("deviceUserExportState.open && Boolean(selectedDeviceId)");
		expect(enroll).toContain('activePanel === "users" || deviceUserExportState.open');
		expect(enroll).toContain("isLoadingDeviceUserExportRows");
		expect(enroll).toContain("Encrypted biometric readiness");
		expect(enroll).toContain("getPortableTemplateEnvelopeValue");
		expect(enroll).toContain('envelope.keySource === "passphrase-scrypt"');
		expect(enroll).toContain("getDeviceUserExportBiometricGaps");
		expect(enroll).toContain("Biometric capture started before export");
		expect(enroll).toContain("Enter the package passphrase before previewing encrypted biometrics");
		expect(enroll).toContain("deviceUserImportState.biometricBundlePassphrase || undefined");
		expect(enroll).not.toContain('const DEVICE_USER_CSV_ENCRYPTED_BUNDLE_AVAILABLE');
		expect(enroll).not.toContain('return DEVICE_USER_CSV_ENCRYPTED_BUNDLE_AVAILABLE');
		expect(enroll).toContain("selectedExportVendorUserIds");
		expect(enroll).toContain("togglePagedExportVendorUserIds");
		expect(enroll).toContain("encryptedBiometricBundle");
		expect(enroll).toContain("Encrypted bundle contract");
		expect(enroll).toMatch(
			/const DEVICE_USER_BIOMETRIC_CSV_COLUMNS = \[\s*"fingerprintTemplate",\s*"faceTemplate",\s*\] as const;/,
		);
		expect(enroll).toContain("DEVICE_USER_SPREADSHEET_TEMPLATE_PREFIX");
		expect(enroll).toContain("encrypted:v2:");
		expect(enroll).toContain("encodeSpreadsheetTemplateValue");
		expect(enroll).toContain("decodeSpreadsheetTemplateValue");
		expect(enroll).toContain("fingerprintTemplate and faceTemplate");
		expect(enroll).toContain("compact values");
		expect(enroll).toContain('return "";');
		expect(enroll).toContain("missing_encrypted_template");
		expect(enroll).not.toContain('"fingerprintRawTemplateBlob",');
		expect(enroll).not.toContain('"faceRawTemplateBlob",');
		expect(enroll).not.toContain('"fingerprintTemplateKeySource",');
		expect(enroll).not.toContain('"faceTemplateKeySource",');
		expect(enroll).not.toContain('"biometricPlaintextExposed",');
		expect(enroll).not.toContain(
			"not_exported_plaintext_use_encrypted_bundle_or_sdk_peer_copy",
		);
		expect(enroll).toContain("DEVICE_USER_BIOMETRIC_CSV_COLUMNS");
		expect(enroll).toContain("getDeviceUserCsvHeaders");
		expect(enroll).toContain("buildDeviceUserImportPayloadFromCsv");
		expect(enroll).toContain("biometricCsvColumns");
		expect(enroll).toContain("Plaintext");
		expect(enroll).toContain("biometric bytes are never written");
		expect(enroll).toContain("Use SDK peer copy when both devices are reachable");
		expect(enroll).toContain("Preview import");
		expect(enroll).toContain("Import CSV file");
		expect(enroll).toContain("Package JSON");
		expect(enroll).toContain("CSV template");
		expect(enroll).toContain("buildDeviceUserImportPayloadFromCsv");
		expect(enroll).toContain("Two template columns");
		expect(enroll).toContain("Transfer mode");
		expect(enroll).toContain("SDK peer copy");
		expect(enroll).toContain("Encrypted bundle passphrase");
		expect(enroll).toContain("Type IMPORT DEVICE USERS");
		expect(enroll).toContain("Run execute as background job");
		expect(enroll).toContain("Import job queued");
		expect(enroll).toContain("Poll:");
		expect(enroll).toContain("executeDeviceUserImport");
		expect(enroll).toContain("previewToken");
		expect(enroll).toContain("Plain biometric exposed");
		expect(enroll).toContain("biometric bytes are never written");
		expect(enroll).toContain("previewDeviceUserExport");
		expect(enroll).toContain("previewDeviceUserImport");
		expect(enroll).toContain("ISAPI source");
		expect(enroll).toContain("SDK source");
		expect(enroll).toContain("Reading source users from the physical device");
		expect(enroll).toContain("deviceUserView");
		expect(enroll).toContain("deviceUserPage");
		expect(enroll).toContain("New records");
		expect(enroll).toContain("Auto-linked");
		expect(enroll).toContain("Rows marked Needs link were saved in HRIS");
		expect(enroll).toContain("saved biometric");
		expect(enroll).toContain("Physical");
		expect(enroll).toContain("Historical HRIS backfill");
		expect(enroll).toContain("Loading enrolled face photo");
		expect(enroll).toContain("Fingerprint truth");
		expect(enroll).not.toContain("Mock 1 fingerprint");
		expect(enroll).not.toContain("Clear mock tally");
		expect(enroll).not.toContain("Mock 1 face");
		expect(enroll).not.toContain("Clear mock face");
		expect(enroll).not.toContain("Sync real face to peers");
		expect(enroll).toContain("fingerprint template blobs are not shown in this normal");
		expect(enroll).toContain("dev mock tallies are kept separate from physical");
		expect(enroll).toContain("Across Hikvision devices");
		expect(enroll).toContain("Best saved tally for this user across configured");
		expect(enroll).toContain("Vendor metadata");
		expect(enroll).toContain("Preview vendor metadata");
		expect(enroll).toContain("Vendor metadata JSON");
		expect(enroll).toContain("Raw source payload");
		expect(enroll).toContain("getDeviceUserVendorMetadata");
		expect(enroll).toContain("formatMetadataPreview");
		expect(enroll).toContain("Copy to all peer devices");
		expect(enroll).toContain("targetDeviceIds,");
		expect(enroll).toContain("one coordinated VM session");
		expect(enroll).not.toContain("for (let index = 0; index < targetDeviceIds.length");
		expect(enroll).toContain(".getDeviceUserPhoto(");
		expect(enroll).toContain("Photo source");
		expect(enroll).toContain("<summary");
		expect(enroll).toContain("getDeviceUserSource");
		expect(enroll).not.toContain("historical shown by filter");
		expect(enroll).not.toContain("deviceUserSource");
		expect(enroll).not.toContain("Current device users");
		expect(enroll).not.toContain("Identity records synced from");
		expect(enroll).not.toContain("Device user sync status");
		expect(enroll).not.toContain("Device logs are synced from the logs page");
		expect(enroll).not.toContain("This does not import attendance logs");
		expect(enroll).not.toContain("Device Enrollment");
		expect(enroll).not.toContain("Enroll Users");
		expect(enroll).not.toContain("Link identity");
		expect(events).not.toContain("Sync logs request accepted");
		expect(events).toContain("Sync device logs started");
		expect(events).toContain("isFetchingSyncPreview && syncPreviewRows.length === 0");
		expect(deviceHooks).toContain("refetchInterval: enabled ? 15 * 1000 : false");

		expect(events).toContain("Sync logs");
		expect(events).toContain("Sync device logs");
		expect(events).toContain("latestSdkEvidenceAgeMs");
		expect(events).toContain("getEventEvidenceTime(latestSdkProbeEvent) > getEventEvidenceTime(latestSdkSavedEvent)");
		expect(events).toContain("latestSdkEvidenceIsOperationSignal");
		expect(events).toContain("SDK operation signal captured");
		expect(events).toContain("Open it, then run/review device-user reconciliation for the same device.");
		expect(events).toContain("SDK event proof");
		expect(events).not.toContain("Browser connected; no recent SDK tap");
		expect(events).toContain("knownSkippedEventCount");
		expect(events).toContain("missingEventCount");
		expect(events).toContain("getSyncProjectedSaveCount");
		expect(events).toContain("getSyncProjectedSkipCount");
		expect(events).toContain("Estimated unsaved");
		expect(events).toContain("Will skip");
		expect(events).toContain("Device logs scanned");
		expect(events).toContain("Saved to HRIS");
		expect(events).toContain("Sync scans device source logs, then classifies each row against HRIS.");
		expect(events).toContain("const [skipMissingEmployeeNo, setSkipMissingEmployeeNo] = useState(false)");
		expect(events).toContain("Skip rows with no employee no.");
		expect(events).toContain("will stay skipped during the source scan");
		expect(events).toContain("Sync scans device source logs, then classifies each row against HRIS.");
		expect(events).not.toContain("Missing saved");
		expect(events).not.toContain("Checking for missing device logs");
		expect(events).toContain("deviceId: device.deviceId,");
		expect(events).toContain("getOptionLabel(eventActionOptions, event.eventAction || event.taxonomy?.eventAction || \"\")");
		expect(events).toContain("skipMissingEmployeeNo,");
		expect(events).toContain("targetImportCount: device.targetImportCount,");
	});
});
