import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const readAppFile = (path: string) => readFileSync(join(process.cwd(), path), "utf8");

describe("admin device user and log sync UI contract", () => {
	it("keeps device user sync separate from device log sync", () => {
		const manage = readAppFile("app/routes/admin/devices/manage.tsx");
		const enroll = readAppFile("app/routes/admin/devices/enroll.tsx");
		const events = readAppFile("app/routes/admin/devices/events.tsx");
		const deviceHooks = readAppFile("app/lib/hooks/useDevices.ts");
		const deviceService = readAppFile("app/services/devices.service.ts");
		const deviceController = readAppFile("../hris-api/app/device/device.controller.ts");

		expect(deviceHooks).toContain("useDeviceHealthMap");
		expect(events).toContain('data-testid="device-filter-reachability-dot"');

		expect(enroll).toContain("Merge users");
		expect(manage).toContain("Sync Center");
		expect(manage).toContain("View Device Users");
		expect(manage).toContain("View Device Events");
		// Devices table shows live reachability from GET /api/device/:id/health.
		expect(manage).toContain("useDeviceHealthMap");
		expect(manage).toContain('label: "Status"');
		expect(manage).toContain('data-testid="device-reachability-status"');
		expect(manage).toContain("getDeviceReachabilityBadgeClass");
		expect(enroll).toContain('title="Merge device users"');
		expect(manage).toContain('data-field-path="config.vendor"');
		expect(manage).toContain("Device vendor");
		expect(manage).toContain("HRIS applies the correct runtime settings automatically.");
		expect(manage).toContain("Runtime config");
		expect(manage).toContain("Runtime path");
		expect(manage).toContain("Auto local bridge");
		expect(manage).toContain("Direct device only");
		expect(manage).toContain("buildHikvisionRuntimeConfig");
		expect(manage).toContain('data-field-path="config.employeeKioskLoginEnabled"');
		expect(manage).toContain("Enable biometric kiosk login");
		expect(manage).toContain("sign in the employee kiosk automatically");
		expect(manage).not.toContain('data-field-path="config.source"');
		expect(manage).not.toContain('data-field-path="config.sdkPort"');
		expect(manage).not.toContain('data-field-path="config.webhookPath"');
		expect(manage).not.toContain("Runtime adapter *");
		expect(manage).not.toContain("Callback path");
		expect(manage).not.toContain("Internal adapter key");
		expect(manage).toContain('next.set("action", "sync-review")');
		expect(manage).toContain('next.set("action", "device-users")');
		expect(manage).not.toContain("enroll-users");
		expect(enroll).toContain("Overview");
		expect(enroll).toContain("<Tabs");
		expect(enroll).toContain("Device Users");
		expect(enroll).toContain("<span>Device</span>");
		expect(enroll).toContain("<span>Device IP</span>");
		expect(enroll).toContain("<span>Status</span>");
		expect(enroll).toContain("<span>Source users</span>");
		expect(enroll).toContain("<span>HRIS users</span>");
		expect(enroll).toContain("From device");
		expect(enroll).toContain("Gap");
		expect(enroll).toContain("Needs match");
		expect(enroll).toContain("Saved in HRIS");
		expect(enroll).toContain("Needs link");
		expect(enroll).toContain("source");
		expect(enroll).toContain("saved");
		expect(enroll).toContain("Listener");
		expect(enroll).toContain('activePanel === "overview" || activePanel === "users" || isListenerDetailsOpen');
		expect(enroll).toContain("Open");
		expect(enroll).toContain("<span>Last sync</span>");
		expect(enroll).toContain("Actions</span>");
		expect(enroll).toContain("xl:grid-cols-[minmax(190px,1.45fr)_124px_128px_150px_156px_112px_96px]");
		expect(enroll).toContain("whitespace-normal break-words");
		expect(enroll).toContain("openPhysicalDeviceUsers");
		// Deep-links: peer tally device name, merge user id, recovery source/target.
		expect(enroll).toContain("openDeviceUserDeepLink");
		expect(enroll).toContain("deviceUserDetails");
		expect(enroll).toContain("Open device user details");
		expect(enroll).toContain("Deep-link to vendor user");
		expect(enroll).toContain("Choose a device first");
		expect(enroll).toContain('data-testid="device-user-summary-toolbar"');
		expect(enroll).toContain("flex min-w-0 flex-wrap items-center gap-2");
		expect(enroll).toContain("Back to device summary");
		expect(enroll).toContain("Refresh summary");
		expect(enroll).toContain("Search device users across available devices");
		expect(enroll).toContain("Find user on devices");
		expect(enroll).toContain('whitespace-nowrap">Sync status');
		expect(enroll).toContain("Still checking available Hikvision devices");
		expect(enroll).toContain("No device-user results have been read yet");
		expect(enroll).toContain("Searching that device");
		expect(enroll).toContain("Recent saved activity");
		expect(enroll).toContain("Shows callback, reconcile, and backfill rows saved for this");
		expect(enroll).toContain("device.");
		expect(enroll).toContain("Refresh activity");
		expect(enroll).toContain("formatActivityOrigin");
		expect(enroll).toContain("formatActivityDetail");
		expect(enroll).toContain("rawSdkPersistence");
		expect(enroll).toContain("useDeviceActivity");
		expect(enroll).toContain("Device-user sync");
		expect(enroll).toContain("Review user sync");
		expect(enroll).not.toContain("Sync first");
		expect(enroll).toContain("Change employee link");
		expect(enroll).toContain("Link employee");
		expect(enroll).toContain("Save and link");
		expect(enroll).toContain("Submitting will save current");
		expect(enroll).toContain("device users first, then link the employee");
		expect(enroll).toContain("deviceService.getDeviceUsers");
		expect(enroll).toContain("vendorUserId: linkTarget.vendorUserId");
		expect(enroll).toContain("vendorUserIds");
		expect(enroll).toContain("Math.min(Math.max(sourceVendorUserIdsForQuery.length, 1), 1000)");
		expect(deviceController).toContain("const maxLimit = vendorUserIds.length > 0 ? 1000 : 100");
		expect(enroll).toContain("linkTarget.hrisDeviceUser || null");
		expect(enroll).toContain('status: "UNMATCHED"');
		expect(enroll).toContain("openDbDeviceUsers?.deviceUsers");
		expect(enroll).toContain("mergedDeviceUserRows.length === 0");
		expect(enroll).toContain("CHECKING_LINK");
		expect(enroll).toContain("Checking HRIS link");
		expect(enroll).toContain("LINK_CHECK_FAILED");
		expect(enroll).toContain("Could not verify link");
		expect(enroll).toContain("Search employee name, ID, device ID");
		expect(enroll).toContain("EmployeePickerSelect");
		const employeePicker = readAppFile("app/components/molecules/employee/EmployeePickerSelect.tsx");
		expect(employeePicker).toContain("(data as any)?.data?.pagination?.total");
		expect(employeePicker).toContain("(data as any)?.data || {}");
		expect(enroll).not.toContain("limit: 1000,\n\t\tdocument: true,\n\t\tpagination: true,");
		expect(enroll).toContain("Unlink employee");
		expect(enroll).toContain('title="Unlink employee"');
		expect(enroll).toContain("Confirm this device user should be unlinked");
		expect(enroll).toContain("Device Logs");
		expect(enroll).toContain("Sync Runs");
		expect(enroll).toContain("Review log sync");
		expect(enroll).toContain("Review sync");
		expect(enroll).toContain("rawFingerprintBlob");
		expect(enroll).toContain("rawFaceBlob");
		expect(enroll).toContain("${storedCount} of ${enrolledCount} stored");
		expect(enroll).toContain("All enrolled fingerprint templates stored");
		expect(enroll).toContain("Repair: capture face");
		expect(enroll).toContain("Raw fingerprint templates");
		expect(enroll).toContain("Raw face photo");
		expect(enroll).toContain("fingerprintRawMissing");
		expect(enroll).toContain("faceRawMissing");
		expect(enroll).toContain("Raw blobs only");
		expect(enroll).toContain("biometrics_only");
		expect(enroll).not.toContain("Fingerprint encrypted envelope");
		expect(enroll).not.toContain("Face encrypted envelope");
		expect(enroll).toContain("fastest valid device-user plan");
		expect(enroll).toContain("deviceIds: [selectedDeviceId]");
		expect(enroll).toContain("You can close this window and reopen status");
		expect(enroll).toContain('["Captured", effectiveDeviceUserSyncJobProgress?.biometricCaptured');
		expect(enroll).toContain('["Device no-data", effectiveDeviceUserSyncJobProgress?.biometricFailed');
		expect(enroll).toContain("deviceUserSyncFailureLog");
		expect(enroll).toContain("Recent device no-data");
		expect(enroll).toContain("formatDeviceUserSyncRawFailureReason");
		expect(enroll).toContain("formatDeviceUserSyncRawFailureMessage");
		expect(enroll).toContain("Face image not found on device");
		expect(enroll).toContain("Face image unavailable: unauthorized");
		expect(enroll).toContain("Device returned non-image data");
		expect(enroll).toContain("face_image_not_found_on_device");
		expect(enroll).toContain("face_image_unauthorized");
		expect(enroll).toMatch(
			/\{formatDeviceUserSyncRawFailureReason\(\s*failure\.reason,\s*\)\}/,
		);
		expect(enroll).toMatch(
			/formatDeviceUserSyncRawFailureMessage\(\s*result\.error,\s*\)/,
		);
		expect(enroll).toContain("Building raw-custody plan");
		expect(enroll).toContain("Retry raw blobs only");
		expect(enroll).toContain("What Sync can fix");
		expect(enroll).toContain("missing_device_user_record");
		expect(enroll).toContain("mergeDeviceUserSyncReviewMatrix");
		expect(enroll).toContain("preview?.syncDecisionMatrix");
		expect(enroll).toContain("dryRunPlan.decisionMatrix");
		expect(enroll).toContain("missing_raw_fingerprint_blob: Math.max");
		expect(enroll).toContain("missing_employee_link");
		expect(enroll).toContain("missing_raw_fingerprint_blob");
		expect(enroll).toContain("missing_raw_face_blob");
		expect(deviceService).toContain("stale_count_only_or_live_no_data");
		expect(deviceService).toContain("unsupported_by_sync");
		expect(enroll).toContain("Fastest valid plan");
		expect(enroll).toContain("Fast plan: scoped missing work");
		expect(enroll).toContain("Full source-user reread and already-present rows are skipped");
		expect(enroll).toContain("Missing links");
		expect(enroll).toContain("Already skipped");
		expect(enroll).toContain("Missing links/raw blobs only");
		expect(enroll).toContain("Building missing-record matrix");
		expect(enroll).toContain("Reading source users needed for identity gaps");
		expect(enroll).toContain("Capturing missing fingerprint raw bytes");
		expect(deviceController).toContain("Capturing missing face raw bytes");
		expect(deviceController).toContain("Skipping known no-data rows");
		expect(enroll).toContain('const DEFAULT_BULK_DEVICE_USER_SYNC_MODE: DeviceUserSyncMode = "needs_attention_only"');
		expect(enroll).toContain("Queuing the fastest valid device-user plan from the decision matrix.");
		expect(enroll).not.toContain("Reading source device users");
		expect(enroll).not.toContain("serially captures");
		expect(enroll).toContain("Device-user sync status");
		expect(enroll).toContain("Open device-user sync status");
		expect(enroll).not.toContain(
			"Previous device-user sync status expired after an API restart or cleanup. You can rerun the refresh safely",
		);
		expect(enroll).not.toContain(
			"Previous device-user sync status stopped updating. Start Sync device users again",
		);
		expect(enroll).toContain('open: current.open');
		expect(enroll).toContain('lastProgress: open ? current.lastProgress : null');
		expect(enroll).toContain('status: open ? current.status : "idle"');
		expect(enroll).toContain("biometric credentials");
		expect(enroll).toContain("Current credential");
		expect(enroll).toContain("Already present");
		expect(enroll).toContain("Raw custody when evidenced");
		expect(enroll).toContain("deviceUserSyncStatusBubble");
		expect(enroll).toContain("Merge users");
		expect(enroll).toContain('title="Merge device users"');
		// Failed inventory reads must show Unavailable, never fake zero + all-missing.
		expect(enroll).toContain("Unavailable");
		expect(enroll).toContain("readFailed");
		expect(enroll).toContain("merge-device-read-failed-");
		expect(enroll).toContain(
			"Issue counts are not computed for devices that failed inventory read",
		);
		expect(enroll).toContain("Checking which Hikvision devices are available (up to 10 seconds).");
		expect(enroll).toContain("offline or unavailable skipped");
		expect(enroll).toContain("Searching live device-user records");
		expect(enroll).toContain("No live device-user records matched this search");
		expect(enroll).toContain("Merge needs at least two available devices.");
		expect(enroll).toContain("deviceService.getDeviceHealth(deviceId");
		expect(enroll).toContain('result.value?.summary?.status === "online"');
		expect(enroll).not.toContain("typeof preview.vendorUserCount === \"number\"");
		expect(enroll).not.toContain("DeviceLiveReadinessStrip");
		expect(enroll).not.toContain("Checking DB + live path");
		expect(enroll).not.toContain("useDeviceLiveReadiness");
		expect(enroll).not.toContain("proveLivePath");
		expect(enroll).not.toContain("isSyncCenterReviewOpen");
		expect(enroll).toContain('deviceUserView === "source"');
		expect(enroll).toContain('status === "source_unavailable"');
		expect(enroll).toContain('preview.status === "saved_preview"');
		expect(enroll).toContain('if (status === "saved_preview") return "Unavailable";');
		expect(enroll).toContain('options.unavailableLabel || "Unavailable"');
		expect(enroll).not.toContain("Read separately");
		expect(enroll).not.toContain("Saved preview");
		expect(enroll).toContain('return "Not checked";');
		expect(enroll).toContain("Review merge by unique ID");
		// Auto-resolve uses richest sources (button copy may evolve; keep behavior string).
		expect(enroll).toMatch(/richest sources|recommended sources|Auto-resolved/);
		expect(deviceService).toContain("{ timeoutMs: 300_000 }");
		expect(enroll).toContain("Enrollment counts alone do not authorize biometric copying");
		expect(enroll).toContain("No fingerprint copy is recommended");
		expect(enroll).toContain("No face copy is recommended");
		expect(enroll).toMatch(
			/fingerprint\?\.status ===\s*"raw_blob_present"/,
		);
		expect(enroll).toContain('face?.status === "raw_blob_present"');
		expect(enroll).toContain("selected unique ID");
		expect(enroll).toContain("executable peer copy");
		expect(enroll).toContain("Select all in scope");
		expect(enroll).toContain("Deselect scope");
		expect(enroll).toContain("selectedUserKeys");
		expect(enroll).toContain("mergeCredentialTruth");
		expect(enroll).toContain("Issue: ${mergePlural(issueCount, \"device\")}");
		expect(enroll).toContain("Expected active devices");
		expect(enroll).toContain("Unique IDs");
		expect(enroll).toContain("Device ID records");
		expect(enroll).toContain("Needs decision");
		// Top chip labels come from MERGE_CHIP_CONTRACT via contractById.*.label
		expect(enroll).toContain("contractById.peer_copy.label");
		expect(enroll).toContain("contractById.fingerprint.label");
		expect(enroll).toContain("contractById.face.label");
		expect(enroll).toContain("Include card residual");
		expect(enroll).toContain("includeCardResidual");
		expect(enroll).toContain("sdkMergeDecisionPeopleCount");
		expect(enroll).toContain("sdkMergeMissingPeopleCount");
		expect(enroll).toContain("MERGE_CHIP_CONTRACT");
		expect(enroll).toContain("sdkMergeTopChips");
		expect(enroll).toContain("duplicate source row");
		expect(enroll).toContain("collapsed into the matching unique IDs");
		expect(enroll).toContain("Needs review IDs");
		expect(enroll).toContain("SdkMergeListMode");
		expect(enroll).toContain("sdkMergeUniqueRows");
		expect(enroll).toContain("sdkMergeRecordRows");
		expect(enroll).toContain("sdkMergeWriteRows");
		expect(enroll).toContain('sdkMergeListMode === "issues"');
		expect(enroll).toContain("? sdkMergeReviewRows");
		expect(enroll).toContain("sdkMergeUniqueIssueCount");
		expect(enroll).toContain("sdkMergeUniqueIssueDeviceCount");
		expect(enroll).toContain("sdkMergeIssueRowsForUser");
		expect(enroll).not.toContain("{ value: \"all\", label: \"Issue details\", count: sdkMergeRows.length }");
		expect(enroll).toContain("setSdkMergeListMode");
		expect(enroll).toContain("setSdkMergeDeviceListMode");
		expect(enroll).toContain("Linked record");
		expect(enroll).toContain("Connected");
		expect(enroll).toContain("Missing");
		expect(enroll).toContain("SdkMergeSourceReviewState");
		expect(enroll).toContain("selectedSdkMergeSourceReviewRow");
		expect(enroll).toContain("Compare the current device truth against available source records.");
		expect(enroll).toContain("Review journey");
		expect(enroll).toContain("Open review journey");
		expect(enroll).toContain("Current");
		expect(enroll).toContain("Recommended");
		expect(enroll).toContain("Available for review");
		expect(enroll).toContain("Per-device impact");
		expect(enroll).toContain("IDs read");
		expect(enroll).toContain("sdkMergeRowMatchesDevice");
		expect(enroll).toContain("row.targetDeviceId === deviceId");
		expect(enroll).toContain("Showing");
		expect(enroll).toContain("Page {safeSdkMergePage} of {sdkMergeTotalPages}");
		expect(enroll).toContain("Review selected merge");
		// Agent B Image A honesty: executable copies, not selection size
		expect(enroll).toContain("sdkMergeSelectedWriteMatrix");
		expect(enroll).toContain("merge-ui-truth-counts");
		expect(enroll).toContain("buildMergePeerCopyCta");
		expect(enroll).toContain("sdkMergePeerCopyCta");
		expect(enroll).toContain("sdkMergePeerCopyCta.disabled");
		expect(enroll).toContain("sdkMergePeerCopyCta.label");
		expect(enroll).toContain("countSdkMergeExecutablePeerCopies");
		expect(enroll).toContain("isSdkMergeExecutablePeerCopyRow");
		expect(enroll).toContain("sdkMergeSelectedExecutablePeerCopies");
		expect(enroll).toContain("sdkMergeCanStartPeerCopy");
		expect(enroll).toContain("0 executable peer copies");
		expect(enroll).toContain("No peer copies for this selection");
		expect(enroll).toContain("Executable peer copies");
		expect(enroll).toContain("Physical peer creates (sum of COPY)");
		expect(enroll).toContain("Excluded from scope");
		expect(enroll).toContain("Peer creates by target");
		expect(enroll).toContain("Peer creates by source");
		expect(enroll).toContain("missing peers to create on that panel");
		expect(enroll).toContain("peer creates leaving this source");
		expect(enroll).toContain("formatMergeSourceDeviceTile");
		expect(enroll).toContain("formatMergeTargetDeviceTile");
		expect(enroll).toContain("Selected ID write matrix");
		expect(enroll).toContain("No-op rows (COPY 0)");
		expect(enroll).toContain("Hide no-op IDs");
		expect(enroll).toContain("sdkMergeShowNoOpRows");
		expect(enroll).toContain("Physical source");
		expect(enroll).toContain("Peer copy attempts");
		expect(enroll).toContain("Fingerprint gaps");
		expect(enroll).toContain("Face gaps");
		expect(enroll).toContain("setSelectedMergeUser(row.key)");
		expect(enroll).toContain("Locked job scope");
		expect(enroll).toContain('"Authenticated"');
		expect(enroll).toContain('"Excluded"');
		expect(enroll).toContain("credentialed protocol response");
		expect(enroll).toContain("checkedAt");
		expect(enroll).toMatch(
			/This is the frozen source\/target matrix from the job\s+start request\./,
		);
		expect(enroll).toContain("sdkMergeState.status !== \"loading\" && !hasSdkMergeJob");
		expect(enroll).toContain("Targets receiving copies");
		expect(enroll).toContain("Physical sources used");
		expect(enroll).toContain("Progress estimate");
		expect(enroll).toContain("Current phase");
		expect(enroll).toContain("UI polling");
		expect(enroll).toContain("Backend heartbeat");
		expect(enroll).toContain("No detailed backend heartbeat yet");
		expect(enroll).toContain(
			"Physically retained increases only after a target reread proves the credential stayed on the panel",
		);
		expect(enroll).toContain("Physically retained (reread)");
		expect(enroll).toContain("Fingerprint retained");
		expect(enroll).toContain("Face retained");
		expect(enroll).toContain("Gap totals refresh after the terminal five-device reread");
		expect(enroll).toContain("Already matched");
		expect(enroll).toContain("This job was started before detailed merge telemetry was available.");
		expect(enroll).toContain("Copy failures by path");
		expect(enroll).toMatch(
			/Grouped from backend progress\. Latest rows below may be\s+capped\./,
		);
		expect(enroll).toContain("sdkMergeJobCopyFailurePairs");
		expect(deviceService).toContain("copyFailureSummary");
		expect(deviceController).toContain("copyFailureSummary: job.copyFailureSummary");
		expect(enroll).toContain("Back to review");
		// Forbidden: selected unique ID count as primary CTA work number.
		expect(enroll).not.toContain(
			"Review selected merge (${sdkMergeSelectedUniqueCount})",
		);
		expect(enroll).toContain("buildMergeReviewOpenCta");
		expect(enroll).toContain("sdkMergeReviewOpenCta.label");
		// Forbidden Image A lie: CTA labeled by selected unique ID count
		expect(enroll).not.toContain(
			"Start peer copy job (${sdkMergeSelectedUniqueCount} IDs)",
		);
		expect(enroll).not.toMatch(
			/Start peer copy \(\$\{sdkMergeSelectedUniqueCount\}/,
		);
		expect(enroll).not.toContain("sdkMergePreviewOnly");
		expect(enroll).not.toContain("Preview mode is on.");
		expect(enroll).not.toContain("Preview only");
		expect(enroll).toContain("<span>Fingerprint</span>");
		expect(enroll).toContain("<span>Face</span>");
		expect(enroll).toContain("<span>Card</span>");
		expect(enroll).toContain("SdkMergeCredentialPickerState");
		expect(enroll).toContain("Credential source");
		expect(enroll).toContain("Choose which device should supply this credential.");
		expect(enroll).toContain("truth.present");
		expect(enroll).toContain("truth.expected");
		expect(enroll).toContain("truth.connectedDevices");
		expect(enroll).toContain("truth.missingDevices");
		expect(enroll).toContain("CheckCircle2");
		expect(enroll).toContain("Review sources");
		expect(enroll).not.toContain("Hide details");
		expect(enroll).not.toContain("Source comparison");
		expect(enroll).not.toContain("Finger / Face / Card");
		expect(enroll).not.toContain("Dry-run only for now");
		expect(enroll).not.toContain("dry-run mode prevents writes");
		expect(enroll).not.toContain("Dry run is on.");
		expect(enroll).toMatch(/Peer-copy ready|contractById\.peer_copy/);
		expect(enroll).toContain("Credential convergence");
		expect(enroll).toContain("Fingerprint and face are planned independently");
		expect(enroll).toContain("Select ready operations");
		expect(enroll).toContain('"Potential operations"');
		expect(enroll).toContain("sdkMergePotentialOperationsUiTotal");
		expect(enroll).toContain("sdkMergePotentialOperationSummary");
		expect(enroll).toContain("totalPotentialOperations");
		expect(enroll).toContain("byModality");
		expect(enroll).toContain("includeCardResidual");
		expect(enroll).toContain("modality !== \"card\"");
		expect(enroll).toContain('"Ready now"');
		expect(enroll).toContain('"Agent recovery"');
		expect(enroll).toContain('"Ownership / enroll block"');
		expect(enroll).toContain("Agent recovery: ${formatSdkMergeRecoveryStage(write)}");
		expect(enroll).toContain("Start recovery");
		expect(enroll).toContain("Residual left");
		expect(enroll).toContain("credentialRecoveryStageLabel");
		expect(enroll).toContain("job.progressLabel");
		expect(enroll).toContain("credentialRecoveryJob.lastAdvancementAt");
		expect(enroll).toContain("credentialRecoveryJob.activeTask");
		expect(enroll).toContain("Observability defect");
		expect(enroll).toContain("credentialRecoveryJob.latestError.code");
		expect(enroll).toContain("credentialRecoveryJob.latestError.retryable");
		expect(enroll).toContain('credentialRecoveryJob.status === "completed"');
		expect(enroll).toContain("(credentialRecoveryJob.counters?.verified ?? 0) > 0");
		expect(enroll).toContain("agent can write these (richest source)");
		expect(enroll).toContain("Red = true dual-owner");
		expect(enroll).not.toContain("SDK_MERGE_PHYSICAL_ACTION_REASONS");
		expect(enroll).toContain(
			"Blocked (true ownership/enroll): ${formatSdkMergePhysicalAction(write)}",
		);
		expect(enroll).toContain("!isSdkMergePhysicalActionRequired(write)");
		expect(enroll).not.toContain("Blocked: exact SDK export/copy probe required");
		expect(enroll).not.toContain('"Blocked / review"');
		expect(enroll).toContain("Review credential-only writes");
		expect(enroll).toContain("does not rewrite the user record, cards, validity");
		expect(enroll).toContain('mode: "credentials"');
		expect(enroll).toContain("selectedCredentialWriteIds");
		expect(deviceService).toContain('mode?: "users" | "credentials"');
		expect(deviceService).toContain("credentialWrites?: Array");
		expect(enroll).toContain("Keep");
		expect(enroll).toContain("Clear");
		expect(enroll).toContain("configuredDeviceIds.length < 2");
		expect(enroll).toContain("sdkMergeBlockingCount");
		expect(enroll).toContain("Read from device");
		expect(enroll).toContain("Current view");
		expect(enroll).toContain("HRIS records");
		expect(enroll).toContain("Linked employees");
		expect(enroll).toContain("Needs link");
		expect(enroll).toContain("SOURCE_ONLY");
		expect(enroll).toContain("Refresh source users");
		expect(enroll).toContain('aria-label="Export device users"');
		expect(enroll).toContain('aria-label="Import device users"');
		expect(enroll).toContain("Export device users");
		expect(enroll).toContain("Import device users");
		expect(enroll).toContain("Current page");
		expect(enroll).toContain("Current filter");
		expect(enroll).toContain("Selected rows");
		expect(enroll).toContain("All device users");
		expect(enroll).toContain("deviceUserExportScopeLabel");
		expect(enroll).toContain("deviceUserExportScopeCount");
		expect(enroll).toContain("DeviceUserExportFormat");
		expect(enroll).toContain("CSV");
		expect(enroll).toContain("Excel");
		expect(enroll).toContain("Package JSON");
		expect(enroll).toContain("Spreadsheet custody rows");
		expect(enroll).toContain("Native Excel .xlsx workbook");
		expect(enroll).toContain("XLSX.utils.json_to_sheet");
		expect(enroll).toContain("downloadDeviceUserExport");
		expect(enroll).toContain("deviceUserExportState.open && Boolean(selectedDeviceId)");
		expect(enroll).toContain('activePanel === "users" || deviceUserExportState.open');
		expect(enroll).toContain("isLoadingDeviceUserExportRows");
		expect(enroll).toContain("Biometric readiness");
		expect(enroll).toContain("Checking export readiness");
		expect(enroll).toContain("Preview or export will not change the device.");
		expect(enroll).toContain("getRawFingerprintBlobCell");
		expect(enroll).toContain("decodeRawBiometricBlobCell");
		expect(enroll).toContain("encodeRawFingerprintBlobCell");
		expect(enroll).toContain("decodeRawFingerprintBlobCell");
		expect(enroll).toContain("FP${fingerPrintId}");
		expect(enroll).toContain("fingerprintRawTemplates");
		expect(enroll).toContain("getDeviceUserExportBiometricGaps");
		expect(enroll).not.toContain("Biometric capture started before export");
		expect(enroll).not.toContain("Enter the package passphrase before previewing encrypted biometrics");
		expect(enroll).not.toContain("deviceUserImportState.biometricBundlePassphrase || undefined");
		expect(enroll).not.toContain('const DEVICE_USER_CSV_ENCRYPTED_BUNDLE_AVAILABLE');
		expect(enroll).not.toContain('return DEVICE_USER_CSV_ENCRYPTED_BUNDLE_AVAILABLE');
		expect(enroll).toContain("selectedExportVendorUserIds");
		expect(enroll).toContain("togglePagedExportVendorUserIds");
		expect(enroll).toContain("rawBiometricPackage");
		expect(enroll).toContain("Biometric custody package");
		expect(enroll).toMatch(
			/const DEVICE_USER_SDK_CSV_COLUMNS = \[\s*"vendorUserId",\s*"displayName",\s*"userType",\s*"rawFingerprintBlob",\s*"rawFaceBlob",?\s*\] as const;/,
		);
		expect(enroll).toContain(
			"const getDeviceUserCsvHeaders = () => [...DEVICE_USER_SDK_CSV_COLUMNS];",
		);
		expect(enroll).not.toContain("DEVICE_USER_SPREADSHEET_TEMPLATE_PREFIX");
		expect(enroll).not.toContain("encrypted:v2:");
		expect(enroll).not.toContain("encodeSpreadsheetTemplateValue");
		expect(enroll).not.toContain("decodeSpreadsheetTemplateValue");
		expect(enroll).toContain("rawFingerprintBlob and rawFaceBlob");
		expect(enroll).toContain("raw evidenced biometric blobs");
		expect(enroll).toContain('return "";');
		expect(enroll).toContain("missing_raw_blob");
		expect(enroll).toContain("fingerprintRawTemplateBlob");
		expect(enroll).toContain("faceRawTemplateBlob");
		expect(enroll).not.toContain('"fingerprintTemplateKeySource",');
		expect(enroll).not.toContain('"faceTemplateKeySource",');
		expect(enroll).not.toContain('"biometricPlaintextExposed",');
		expect(enroll).not.toContain(
			"not_exported_plaintext_use_encrypted_bundle_or_sdk_peer_copy",
		);
		expect(enroll).toContain("DEVICE_USER_BIOMETRIC_CSV_COLUMNS");
		expect(enroll).toContain("getDeviceUserCsvHeaders");
		expect(enroll).toContain("buildDeviceUserImportPayloadFromCsv");
		expect(enroll).toContain("biometricCsvColumns");
		expect(enroll).toContain("raw_evidenced_blobs_allowed_for_admin_device_user_sync_package");
		expect(enroll).toContain("Missing cells must stay explicit");
		expect(enroll).toContain("The SDK export has exactly five user columns");
		expect(enroll).toContain("drag &amp; drop (or choose) a 5-column CSV");
		expect(enroll).toContain("Package data (rawPackage)");
		expect(enroll).toContain("Preview import");
		expect(enroll).toContain("Drag & drop CSV here");
		expect(enroll).toContain("device-user-import-dropzone");
		expect(enroll).toContain("onDrop");
		expect(enroll).toContain("onDragOver");
		expect(enroll).toContain("dataTransfer");
		expect(enroll).toContain("dataTransfer?.files");
		expect(enroll).toContain("applyDeviceUserImportFile");
		expect(enroll).toContain("isDeviceUserImportDragging");
		expect(enroll).toContain("five columns:");
		expect(enroll).not.toContain("seven-column");
		// Template columns are exactly 5 — no status columns in DEVICE_USER_SDK_CSV_COLUMNS.
		expect(enroll).not.toMatch(
			/const DEVICE_USER_SDK_CSV_COLUMNS = \[[^\]]*fingerprintStatus/,
		);
		expect(enroll).not.toMatch(
			/const DEVICE_USER_SDK_CSV_COLUMNS = \[[^\]]*faceStatus/,
		);
		expect(enroll).toContain("Package JSON");
		expect(enroll).toContain("CSV template");
		expect(enroll).toContain("buildDeviceUserImportPayloadFromCsv");
		expect(enroll).toContain("Spreadsheet import");
		expect(enroll).toContain("Transfer mode");
		expect(enroll).toContain("Reachable source copy");
		expect(enroll).toContain("Package data");
		// CSV blob packages (FP1( / long base64 face) default UI transfer mode to rawPackage.
		expect(enroll).toContain("Package data (rawPackage)");
		expect(enroll).toContain("looksLikeCsvRawBiometricPackageText");
		expect(enroll).toContain("inferDeviceUserImportBiometricTransferMode");
		expect(enroll).toContain("/FP\\d+\\s*\\(/i");
		expect(enroll).toContain("CSV blob packages (FP1( / long base64) default to package data write path");
		expect(enroll).toContain("packageHasRawBlobs");
		expect(enroll).toContain('? "rawPackage"');
		expect(enroll).toContain("payload?.rawBiometricPackage?.present");
		// Execute forces rawPackage when the package carries raw biometric blobs.
		expect(enroll).toContain(
			"Drag-drop CSV with FP/face blobs always writes via rawPackage (not sdkPeerCopy).",
		);
		expect(deviceHooks).toContain("usePreviewDeviceUserImport");
		expect(deviceHooks).toContain("useExecuteDeviceUserImport");
		expect(enroll).not.toContain("Encrypted bundle passphrase");
		expect(enroll).toContain("Type IMPORT DEVICE USERS");
		expect(enroll).toContain("Run execute as background job");
		expect(enroll).toContain("device-user-import-job-progress");
		expect(enroll).toContain("Import job running");
		expect(enroll).toContain("useDeviceUserImportJob");
		expect(enroll).toContain("Writing biometrics");
		expect(enroll).toContain("executeDeviceUserImport");
		expect(enroll).toContain("previewToken");
		expect(enroll).toContain("package data used");
		expect(enroll).toContain("rawBiometricTemplateBytes");
		expect(enroll).toContain("previewDeviceUserExport");
		expect(enroll).toContain("previewDeviceUserImport");
		expect(enroll).toContain("ISAPI source");
		expect(enroll).toContain("SDK source");
		expect(enroll).toContain("Reading source users from the physical device");
		expect(enroll).toContain("deviceUserView");
		expect(enroll).toContain("deviceUserPage");
		expect(enroll).toContain('if (view === "open") next.set("deviceUserStatus", "UNMATCHED")');
		expect(enroll).toContain(
			'(deviceUserView === "shown" || deviceUserView === "source")',
		);
		expect(enroll).toContain("New records");
		expect(enroll).toContain("What Sync can fix");
		expect(enroll).toContain("missing_device_user_record");
		expect(enroll).toContain("missing_raw_fingerprint_blob");
		expect(enroll).toContain("missing_raw_face_blob");
		expect(enroll).toContain("Fastest valid plan");
		expect(enroll).toContain("Building missing-record matrix");
		expect(enroll).toContain("Reading source users needed for identity gaps");
		expect(enroll).toContain("Already present");
		expect(enroll).toContain("Skip rows already present in HRIS unless a forced repair is selected");
		expect(enroll).toContain("Saved-state first");
		expect(enroll).toContain("Missing employee links");
		expect(enroll).toContain("Auto-linked");
		expect(enroll).toContain("Rows marked Needs link were saved in HRIS");
		expect(enroll).toContain("saved biometric");
		expect(enroll).toContain("Physical");
		expect(enroll).toContain("Historical HRIS backfill");
		expect(enroll).toContain("Loading enrolled face photo");
		expect(enroll).toContain("Fingerprint truth");
		expect(enroll).not.toContain("Mock 1 fingerprint");
		expect(enroll).not.toContain("Clear mock tally");
		expect(enroll).not.toContain("Mock 1 face");
		expect(enroll).not.toContain("Clear mock face");
		expect(enroll).not.toContain("Sync real face to peers");
		expect(enroll).toContain("Raw fingerprint templates");
		expect(enroll).toContain("Raw fingerprint base64 copied");
		expect(enroll).toContain("Across Hikvision devices");
		expect(enroll).toContain("Best saved tally for this user across configured");
		expect(enroll).toContain("Vendor metadata");
		expect(enroll).toContain("Preview vendor metadata");
		expect(enroll).toContain("Vendor metadata JSON");
		expect(enroll).toContain("Raw source payload");
		expect(enroll).toContain("getDeviceUserVendorMetadata");
		expect(enroll).toContain("formatMetadataPreview");
		expect(enroll).toContain("Copy to all peer devices");
		expect(enroll).toContain("targetDeviceIds,");
		expect(enroll).toContain("startHikvisionPeerCopyJob");
		expect(enroll).toContain("durable peer-copy job");
		expect(enroll).not.toContain("for (let index = 0; index < targetDeviceIds.length");
		expect(enroll).toContain(".getDeviceUserPhoto(");
		expect(enroll).toContain("Photo source");
		expect(enroll).toContain("<summary");
		expect(enroll).toContain("getDeviceUserSource");
		expect(enroll).not.toContain("historical shown by filter");
		expect(enroll).not.toContain("deviceUserSource");
		expect(enroll).not.toContain("Current device users");
		expect(enroll).not.toContain("Identity records synced from");
		expect(enroll).not.toContain("Device user sync status");
		expect(enroll).not.toContain("Device logs are synced from the logs page");
		expect(enroll).not.toContain("This does not import attendance logs");
		expect(enroll).not.toContain("Device Enrollment");
		expect(enroll).not.toContain("Enroll Users");
		expect(enroll).not.toContain("Link identity");
		expect(events).not.toContain("Sync logs request accepted");
		expect(events).toContain("Sync device logs started");
		expect(events).toContain("showSyncPreviewSkeleton");
		expect(events).toContain("Sync-preview only when Sync logs modal is open");
		expect(deviceHooks).toContain("options.refetchInterval ?? false");
		expect(deviceService).toContain("{ timeoutMs: 15_000, signal: options.signal }");
		expect(deviceService).toContain("timeoutMs: 15_000");
		expect(deviceHooks).toContain("meta: { timeoutMs: 15_000 }");
		expect(deviceHooks).toContain("queryFn: ({ signal })");
		expect(deviceHooks).toContain("placeholderData: (previous) => previous");
		expect(enroll).toContain("Checking listener status");
		expect(enroll).toContain("Refresh status");
		expect(enroll).toContain("Retry status");
		expect(enroll).toContain("Retry availability");
		expect(enroll).toContain("Refresh tunnels/status");
		expect(enroll).toContain("checks complete");
		expect(enroll).toContain("sdkMergeAvailabilityRequest");
		expect(enroll).toContain("readableDeviceCount");
		expect(enroll).toContain("live inventory read");

		expect(events).toContain("Sync logs");
		expect(events).toContain("Sync device logs");
		expect(events).toContain("latestSdkEvidenceAgeMs");
		expect(events).toContain("const latestSdkEvidenceEvent = latestSdkSavedEvent");
		expect(events).toContain("latestSdkEvidenceIsOperationSignal");
		expect(events).toContain("SDK operation signal captured");
		expect(events).toContain("Listener stopped");
		expect(events).toContain("Login failed");
		expect(events).toContain("HRIS callback post failed");
		expect(events).toContain("HIKVISION_ACTIVE_WORK_EVENTS");
		expect(events).toContain("Active SDK work:");
		expect(events).toContain("Reading fingerprint");
		expect(events).toContain("Reading face");
		expect(events).toContain("Peer ${operation || \"SDK\"} copy attempt");
		expect(events).toContain("callbacks /");
		expect(events).toContain("armed/listening");
		expect(events).toContain("SDK work active");
		expect(enroll).toContain("Live copy now");
		expect(enroll).toContain("Employee now");
		expect(enroll).toContain("Credential stage");
		expect(enroll).toContain("From backend progressEvents");
		expect(enroll).toContain("Latest backend events");
		expect(enroll).toContain("Most recent progressEvents from the API heartbeat");
		expect(enroll).toContain("vm_copy_attempt_started");
		expect(enroll).toContain("Batch copy started");
		expect(events).toContain('device.state !== "login_failed"');
		expect(deviceController).toContain("Listener service is stopped; previous arm/read log entries are historical only.");
		expect(events).toContain("Open it, then run/review device-user reconciliation for the same device.");
		expect(events).toContain("SDK event proof");
		expect(events).not.toContain("Browser connected; no recent SDK tap");
		expect(events).toContain("knownSkippedEventCount");
		expect(events).toContain("missingEventCount");
		expect(events).toContain("getSyncProjectedSaveCount");
		expect(events).toContain("getSyncProjectedSkipCount");
		expect(events).toContain("Will add to Device Events");
		expect(events).toContain("Event to add");
		expect(events).toContain("Source proof");
		expect(events).toContain("Filter after sync");
		expect(events).toContain("Devices ready:");
		expect(events).toContain("Already saved:");
		expect(events).toContain("deviceIsBlocked");
		expect(events).toContain("Rows scanned this pass");
		expect(events).toContain("Saved to HRIS");
		expect(events).toContain("Sync scans device source logs, then classifies each row against HRIS.");
		expect(events).toContain("const [skipMissingEmployeeNo, setSkipMissingEmployeeNo] = useState(false)");
		expect(events).toContain("Skip rows with no employee no.");
		expect(events).toContain("will stay out of Device Events");
		expect(events).toContain("Sync scans device source logs, then classifies each row against HRIS.");
		expect(events).not.toContain("Missing saved");
		expect(events).not.toContain("Checking for missing device logs");
		expect(events).not.toContain("VM listener unknown");
		expect(events).not.toContain("Current inventory");
		expect(events).toContain("deviceId: device.deviceId,");
		expect(events).toContain("getOptionLabel(eventActionOptionsStatic, event.eventAction || event.taxonomy?.eventAction || \"\")");
		expect(events).toContain("skipMissingEmployeeNo,");
		expect(events).toContain("targetImportCount: device.targetImportCount,");
	});
});
