import { Check, Edit, Tag, X, Sparkles } from "lucide-react";
import { Button } from "~/components/atoms/Button";
import { Input } from "~/components/ui/input";
import { DatePicker } from "~/components/ui/date-picker";
import { Label } from "~/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "~/components/ui/select";

interface FieldMappingRowProps {
	field: {
		key: string;
		label: string;
		description?: string;
		autoGenerated?: boolean;
	};
	mapping?: string;
	defaultValue?: string;
	headers: string[];
	onMappingChange: (key: string, header: string | null) => void;
	onDefaultChange: (key: string, value: string | null) => void;
	isRequired?: boolean;
	isSystem?: boolean;
	selectOptions?: Array<{ value: string; label: string }>;
}

export function FieldMappingRow({
	field,
	mapping,
	defaultValue,
	headers,
	onMappingChange,
	onDefaultChange,
	isRequired = false,
	isSystem = false,
	selectOptions,
}: FieldMappingRowProps) {
	const getAutoGeneratedHint = (fieldKey: string): string => {
		if (fieldKey === "EMAIL") return "Generated from employee name";
		if (fieldKey === "SCHEDULE") return "Generated from department";
		if (fieldKey === "ROLE") return "Generated from level";
		return "Generated automatically";
	};

	const isMapped = !!mapping;
	const isDefault = defaultValue !== undefined;
	const isExact = mapping === field.key;
	const isActive = isMapped || isDefault;
	const isDateField = ["HIRE_DATE", "START_DATE", "END_DATE", "BIRTHDAY"].includes(field.key);
	const isAutoSystemPending = isSystem && field.autoGenerated && !isActive;

	const borderColor = isRequired
		? isActive
			? "border-gray-200"
			: "border-red-200"
		: isSystem
			? isAutoSystemPending
				? "border-emerald-200"
				: isActive
					? "border-gray-200"
					: "border-purple-200"
			: "border-transparent";

	const bgColor = isRequired
		? isActive
			? "bg-gray-50/50"
			: "bg-white"
		: isSystem
			? isAutoSystemPending
				? "bg-emerald-50/40"
				: isActive
					? "bg-gray-50/50"
					: "bg-white"
			: isActive
				? "bg-gray-50/50"
				: "";

	const labelColor = isRequired
		? isActive
			? "text-gray-700"
			: "text-red-700"
		: isSystem
			? isAutoSystemPending
				? "text-emerald-700"
				: isActive
					? "text-gray-700"
					: "text-purple-700"
			: "text-gray-600";

	return (
		<div
			className={`col-span-1 p-3 rounded-lg border transition-all duration-200 group ${bgColor} ${borderColor} ${!isActive && (isRequired || isSystem) ? "shadow-sm" : ""} ${!isActive && !isRequired && !isSystem ? "hover:bg-gray-50 hover:border-gray-200" : ""}`}>
			<div className="space-y-2">
				<div className="flex items-center justify-between">
					<Label
						className={`text-sm font-medium flex items-center gap-1.5 ${labelColor}`}
						title={field.description}>
						{field.label}
						{isRequired && <span className="text-red-500">*</span>}
						{isSystem && <span className="text-purple-500">*</span>}
					</Label>
					{isExact && !isDefault && (
						<span className="text-[10px] text-emerald-600 flex items-center gap-1 font-medium bg-emerald-50 px-1.5 rounded-sm border border-emerald-100">
							<Check className="w-3 h-3" /> Auto
						</span>
					)}
					{isDefault && (
						<span
							className={`text-[10px] flex items-center gap-1 font-medium px-1.5 rounded-sm border ${
								field.autoGenerated
									? "text-blue-600 bg-blue-50 border-blue-200"
									: "text-gray-600 bg-gray-100 border-gray-200"
							}`}>
							{field.autoGenerated ? (
								<>
									<Sparkles className="w-3 h-3" /> Auto Generated
								</>
							) : (
								<>
									<Tag className="w-3 h-3" /> Default
								</>
							)}
						</span>
					)}
				</div>

				{isDefault ? (
					<div className="space-y-1">
						<div className="relative">
							{selectOptions ? (
								<Select
									value={defaultValue || ""}
									onValueChange={(val) => onDefaultChange(field.key, val)}>
									<SelectTrigger className="h-9 pr-8 bg-gray-50 border-gray-200 text-gray-700 focus:ring-gray-200">
										<SelectValue placeholder={`Select ${field.label}`} />
									</SelectTrigger>
									<SelectContent>
										{selectOptions.map((opt) => (
											<SelectItem key={opt.value} value={opt.value}>
												{opt.label}
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							) : isDateField ? (
								<DatePicker
									value={defaultValue || ""}
									onChange={(value) => onDefaultChange(field.key, value)}
									placeholder="Select date"
									className="h-9"
								/>
							) : (
								<Input
									value={defaultValue || ""}
									onChange={(e) => onDefaultChange(field.key, e.target.value)}
									autoFocus={!field.autoGenerated}
									disabled={field.autoGenerated}
									className={`h-9 pr-8 focus-visible:ring-gray-200 ${
										field.autoGenerated
											? "bg-blue-50/50 border-blue-200 text-blue-600 cursor-not-allowed"
											: "bg-gray-50 border-gray-200 placeholder:text-gray-400"
									}`}
									placeholder={
										field.autoGenerated
											? "e.g., j.delacruz@company.com"
											: "Enter static value"
									}
								/>
							)}
							<Button
								variant="ghost"
								size="icon"
								className="h-7 w-7 absolute right-1 top-1 text-gray-400 hover:text-red-500 z-10"
								onClick={(e) => {
									e.stopPropagation();
									onDefaultChange(field.key, null);
								}}
								title="Remove default value (switch to mapping)">
								<X className="w-3.5 h-3.5" />
							</Button>
						</div>
						<p
							className={`text-[10px] flex items-center gap-1 ${
								field.autoGenerated ? "text-blue-600" : "text-gray-500"
							}`}>
							{field.autoGenerated ? (
								<>
									<Sparkles className="w-3 h-3" />{" "}
									{getAutoGeneratedHint(field.key)}
								</>
							) : (
								<>
									<Tag className="w-3 h-3" /> Applied to all rows
								</>
							)}
						</p>
					</div>
				) : isExact ? (
					<div className="relative group/input">
						<div className="w-full h-9 px-3 py-2 bg-emerald-50/50 border border-emerald-200/60 rounded-md text-sm text-emerald-900 flex items-center shadow-sm">
							<span className="text-emerald-500 mr-2 font-mono text-[10px] uppercase font-bold tracking-wider">
								Map:
							</span>
							<span className="font-medium truncate flex-1">{mapping}</span>
							<div className="w-4" />
						</div>
						<div className="absolute right-1 top-1 flex gap-1 opacity-0 group-hover/input:opacity-100 transition-opacity">
							<Button
								variant="ghost"
								size="icon"
								className="h-7 w-7 text-gray-400 hover:bg-gray-100"
								onClick={() => {
									onMappingChange(field.key, null);
									onDefaultChange(field.key, "");
								}}
								title="Switch to default value">
								<Edit className="w-3.5 h-3.5" />
							</Button>
							<Button
								variant="ghost"
								size="icon"
								type="button"
								className="h-7 w-7 text-gray-400 hover:text-red-600 hover:bg-red-50"
								onClick={() => onMappingChange(field.key, null)}
								title="Remove mapping">
								<X className="w-3.5 h-3.5" />
							</Button>
						</div>
					</div>
				) : field.autoGenerated && !isMapped && !isDefault ? (
					<div className="space-y-1">
						<div className="w-full h-9 px-3 py-2 bg-emerald-50 border border-emerald-200 rounded-md text-sm text-emerald-700 flex items-center gap-2">
							<Sparkles className="w-3.5 h-3.5" />
							<span className="font-medium">Auto</span>
						</div>
						<p className="text-[10px] text-emerald-700 flex items-center gap-1">
							<Sparkles className="w-3 h-3" /> {getAutoGeneratedHint(field.key)} if
							blank
						</p>
					</div>
				) : (
					<Select
						value={mapping || ""}
						onValueChange={(val) => {
							if (val === "_manual_input_") {
								onMappingChange(field.key, null);
								onDefaultChange(field.key, "");
							} else {
								onMappingChange(field.key, val);
								onDefaultChange(field.key, null);
							}
						}}>
						<SelectTrigger
							className={`h-9 ${!mapping ? `${isRequired ? "border-red-300 focus:ring-red-200 focus:border-red-400 bg-red-50/10" : isSystem ? "border-purple-300 focus:ring-purple-200" : "border-gray-300"} bg-white` : "border-gray-300 bg-white"}`}>
							<SelectValue placeholder="Select column..." />
						</SelectTrigger>
						<SelectContent>
							{headers.map((header) => (
								<SelectItem key={header} value={header}>
									{header}
								</SelectItem>
							))}
							<div className="h-px bg-gray-100 my-1 mx-1" />
							<SelectItem
								value="_manual_input_"
								className={`font-medium focus:bg-gray-100 ${
									field.autoGenerated
										? "text-blue-600 focus:text-blue-900"
										: "text-gray-600 focus:text-gray-900"
								}`}>
								<span className="flex items-center gap-2">
									{field.autoGenerated ? (
										<>
											<Sparkles className="w-3 h-3" /> Auto Generated
										</>
									) : (
										<>
											<Edit className="w-3 h-3" /> Set Static Value
										</>
									)}
								</span>
							</SelectItem>
						</SelectContent>
					</Select>
				)}
			</div>
		</div>
	);
}
