import type { JobApplicationFormConfig } from "~/types/job-application-form.types";

export const defaultJobApplicationConfig: JobApplicationFormConfig = {
	id: "default-job-application",
	title: "Job Application",
	description: "Apply for this position by filling out the form below",
	submitButtonText: "Submit Application",
	successMessage: "Thank you for your application! We'll review it and get back to you soon.",
	sections: [
		{
			id: "resume-upload",
			title: "Resume Upload",
			description: "Upload your most recent resume or CV",
			fields: [
				{
					id: "resume",
					name: "resume",
					label: "Resume/CV",
					type: "file",
					required: true,
					accept: ".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.gif,.bmp",
					maxSize: 10,
					allowedExtensions: ["pdf", "doc", "docx", "jpg", "jpeg", "png", "webp", "gif", "bmp"],
					helperText: "Upload your resume in PDF, DOC, DOCX, or image format (max 10MB)",
				},
			],
		},
		{
			id: "personal-details",
			title: "Personal Details",
			description: "Tell us about yourself",
			fields: [
				{
					id: "firstName",
					name: "firstName",
					label: "First Name",
					type: "text",
					required: true,
					placeholder: "John",
				},
				{
					id: "lastName",
					name: "lastName",
					label: "Last Name",
					type: "text",
					required: true,
					placeholder: "Doe",
				},
				{
					id: "dateOfBirth",
					name: "dateOfBirth",
					label: "Date of Birth",
					type: "date",
					required: true,
				},
				{
					id: "email",
					name: "email",
					label: "Email Address",
					type: "email",
					required: true,
					placeholder: "john.doe@example.com",
				},
				{
					id: "phone",
					name: "phone",
					label: "Phone Number",
					type: "tel",
					required: true,
					placeholder: "+1 (555) 123-4567",
				},
				{
					id: "location",
					name: "location",
					label: "Current Location",
					type: "text",
					required: true,
					placeholder: "City, Country",
				},
				{
					id: "linkedinProfile",
					name: "linkedinProfile",
					label: "LinkedIn Profile",
					type: "url",
					required: false,
					placeholder: "https://linkedin.com/in/yourprofile",
					helperText: "Optional: Share your LinkedIn profile URL",
				},
			],
		},
		{
			id: "professional-background",
			title: "Professional Background",
			description: "Share your work experience",
			fields: [
				{
					id: "currentJobTitle",
					name: "currentJobTitle",
					label: "Current Job Title",
					type: "text",
					required: false,
					placeholder: "Senior Software Engineer",
				},
				{
					id: "yearsOfExperience",
					name: "yearsOfExperience",
					label: "Years of Experience",
					type: "select",
					required: true,
					options: [
						{ value: "0-1", label: "Less than 1 year" },
						{ value: "1-3", label: "1-3 years" },
						{ value: "3-5", label: "3-5 years" },
						{ value: "5-10", label: "5-10 years" },
						{ value: "10+", label: "10+ years" },
					],
				},
			],
		},
		{
			id: "additional-questions",
			title: "Additional Questions",
			description: "Help us get to know you better",
			fields: [
				{
					id: "whyJoinTeam",
					name: "whyJoinTeam",
					label: "Why do you want to join our team?",
					type: "textarea",
					required: true,
					rows: 4,
					maxLength: 500,
					placeholder: "Tell us what excites you about this opportunity...",
				},
				{
					id: "challengingProject",
					name: "challengingProject",
					label: "Describe a challenging project you've worked on",
					type: "textarea",
					required: true,
					rows: 4,
					maxLength: 500,
					placeholder:
						"Share details about a project that challenged you and what you learned...",
				},
				{
					id: "salaryExpectations",
					name: "salaryExpectations",
					label: "Salary Expectations",
					type: "text",
					required: false,
					placeholder: "$80,000 - $100,000",
					helperText: "Optional: Share your expected salary range",
				},
				{
					id: "availabilityDate",
					name: "availabilityDate",
					label: "When can you start?",
					type: "date",
					required: true,
					minDate: new Date(),
				},
				{
					id: "requiresVisaSponsorship",
					name: "requiresVisaSponsorship",
					label: "I require visa sponsorship",
					type: "checkbox",
					required: false,
					description: "Check this if you need visa sponsorship to work in this location",
				},
				{
					id: "additionalInfo",
					name: "additionalInfo",
					label: "Additional Information",
					type: "textarea",
					required: false,
					rows: 3,
					maxLength: 300,
					placeholder: "Is there anything else you'd like us to know?",
				},
			],
		},
	],
};

export const createJobApplicationConfig = (
	overrides?: Partial<JobApplicationFormConfig>,
): JobApplicationFormConfig => {
	return {
		...defaultJobApplicationConfig,
		...overrides,
		sections: overrides?.sections || defaultJobApplicationConfig.sections,
	};
};
