export const REQUIRED_FIELDS = [
	{ key: "EMP_ID", label: "Employee ID", description: "Unique identifier for the employee" },
	{ key: "NAME", label: "Name", description: "Employee full name" },
	{
		key: "REPORT_TO_EMP_ID",
		label: "Reports To",
		description:
			"Employee ID of direct supervisor. Can reference employees in the same CSV (they'll be linked after creation).",
	},
	{
		key: "POSITION",
		label: "Position",
		description: "Job Title/Position (e.g. Software Engineer)",
	},
	{ key: "DEPARTMENT", label: "Department", description: "Department Name (e.g. Engineering)" },
	{ key: "GENDER", label: "Gender", description: "MALE, FEMALE, or OTHER" },
	{ key: "NATIONALITY", label: "Nationality", description: "e.g. Filipino" },
	{
		key: "BASIC_SALARY",
		label: "Basic Salary",
		description: "Payroll-period basic salary amount",
	},
	{
		key: "DAILY_SALARY",
		label: "Daily Salary",
		description:
			"Optional register Daily Salary (Path A OT: hourly = daily/8). Leave blank for monthly Path B BNPI.",
	},
	{ key: "PAY_FREQUENCY", label: "Pay Frequency", description: "MONTHLY, SEMI_MONTHLY, etc." },
	{
		key: "HIRE_DATE",
		label: "Hire Date",
		description: "Date hired (YYYY-MM-DD or MM/DD/YYYY)",
	},
	{
		key: "START_DATE",
		label: "Start Date",
		description: "Employment start date (if different from hire date)",
	},
];

export const SYSTEM_FIELDS = [
	{ key: "EMAIL", label: "Email", description: "Email address", autoGenerated: true },
	{
		key: "WORKFORCE_SOURCE",
		label: "Workforce Source",
		description: "DIRECT or AGENCY (default: DIRECT)",
	},
	{
		key: "ROLE",
		label: "System Role",
		description: "Optional. If blank, derived from Level role or defaults to hris-employee",
		autoGenerated: true,
	},
	{
		key: "SCHEDULE",
		label: "Schedule",
		description: "Optional. If blank, derived from Department default schedule",
		autoGenerated: true,
	},
];

export const OPTIONAL_FIELDS = [
	{
		key: "LEVEL",
		label: "Level",
		description: "Optional job level. Leave blank when the source workbook has no explicit level.",
	},
	{ key: "TIN", label: "TIN", description: "Tax Identification Number" },
	{
		key: "SECTION",
		label: "Section",
		description: "Optional section under the selected department. Leave blank when ambiguous.",
	},
	{
		key: "PREVIOUS_EMPLOYER",
		label: "Previous Employer",
		description: "Stored as import metadata when supplied",
	},
	{
		key: "CIVIL_STATUS",
		label: "Civil Status",
		description: "Stored as import metadata when supplied",
	},
	{
		key: "NO_OF_DEPENDENTS",
		label: "Dependents",
		description: "Stored as import metadata when supplied",
	},
	{
		key: "DATE_OF_RESIGNATION",
		label: "Source Resignation Date",
		description: "Stored as import metadata when supplied",
	},
	{
		key: "SOURCE_STATUS",
		label: "Source Status",
		description: "Source workbook active/status value",
	},
	{
		key: "SOURCE_WORKBOOK",
		label: "Source Workbook",
		description: "Source-of-truth workbook for the employee row",
	},
	{
		key: "SOURCE_SHEET",
		label: "Source Sheet",
		description: "Source-of-truth sheet for the employee row",
	},
	{
		key: "SOURCE_ROW",
		label: "Source Row",
		description: "Source-of-truth row number for the employee row",
	},
	{ key: "SSS", label: "SSS", description: "Social Security System Number" },
	{ key: "PHILHEALTH", label: "PhilHealth", description: "PhilHealth Number" },
	{ key: "PAGIBIG", label: "Pag-IBIG", description: "Pag-IBIG/HDMF Number" },
	{ key: "DEVICE_ID", label: "Device ID", description: "Device employee ID for enrollment" },
	{ key: "PHONE", label: "Phone", description: "Contact number" },
	{ key: "BIRTHDAY", label: "Date of Birth", description: "YYYY-MM-DD or MM/DD/YYYY" },
	{ key: "PLACE_OF_BIRTH", label: "Place of Birth", description: "City/Province of birth" },
	{ key: "STREET", label: "Address: Street", description: "Street address" },
	{ key: "CITY", label: "Address: City", description: "City" },
	{ key: "STATE", label: "Address: State", description: "Province/State" },
	{ key: "COUNTRY", label: "Address: Country", description: "Country" },
	{ key: "POSTAL_CODE", label: "Address: Zip", description: "Postal/Zip Code" },

	{ key: "WORK_LOCATION", label: "Work Location", description: "ONSITE, REMOTE, or HYBRID" },
	{
		key: "AGENCY_CODE",
		label: "Agency Code",
		description: "Required when WORKFORCE_SOURCE is AGENCY",
	},
	{
		key: "CURRENCY",
		label: "Currency",
		description: "Salary Currency (default: PHP)",
	},
];
