param(
  [string[]]$DeviceIps = @('10.184.37.20', '10.184.37.21', '10.184.37.22', '10.184.37.23', '10.184.37.24', '10.184.37.25'),
  [string]$SshTarget = 'project-truth-hris',
  [string]$FallbackSshTarget = 'infra@10.184.37.19',
  [string]$SshKeyPath = (Join-Path $env:USERPROFILE '.ssh\node-health-appliance_ed25519'),
  [int]$LocalHttpPortBase = 10080,
  [int]$LocalHttpsPortBase = 10443,
  [int]$LocalSdkPortBase = 18000,
  [switch]$StopExisting,
  [switch]$NoFallback
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$runtimeRoot = Join-Path $repoRoot '.runtime\hikvision-remote-device-tunnel'
$pidFile = Join-Path $runtimeRoot 'active.json'
$apiRuntimeEnvPath = Join-Path $repoRoot 'hris-api\.env.development.local'
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$runRoot = Join-Path $runtimeRoot "run-$stamp"
$sshExe = (Get-Command ssh.exe -ErrorAction Stop).Source

$DeviceIps = @(
  $DeviceIps |
    ForEach-Object { [string]$_ } |
    ForEach-Object { $_ -split '[,\s;]+' } |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ }
)

function Stop-ExistingTunnel {
  if (-not (Test-Path -LiteralPath $pidFile)) { return }
  $record = Get-Content -Raw -LiteralPath $pidFile | ConvertFrom-Json
  try {
    Stop-Process -Id $record.ProcessId -Force -ErrorAction Stop
    Write-Host "Stopped Hikvision remote device tunnel PID $($record.ProcessId)"
  } catch {
    Write-Host "Hikvision remote device tunnel PID $($record.ProcessId) is not running"
  }
  Remove-Item -LiteralPath $pidFile -Force -ErrorAction SilentlyContinue
}

function Test-TcpConnect {
  param([string]$HostName, [int]$Port, [int]$TimeoutMs = 1500)
  try {
    $client = [System.Net.Sockets.TcpClient]::new()
    $async = $client.BeginConnect($HostName, $Port, $null, $null)
    if (-not $async.AsyncWaitHandle.WaitOne($TimeoutMs, $false)) {
      $client.Close()
      return $false
    }
    $client.EndConnect($async)
    $client.Close()
    return $true
  } catch {
    return $false
  }
}

function Test-SshTarget {
  param(
    [string]$Target,
    [bool]$UseKey = $false
  )
  $previous = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  try {
    # Fallback LAN target (infra@10.184.37.19) requires the appliance key.
    # Probing without -i makes BatchMode fail even when keyed SSH works, which
    # blocked the entire Hikvision device tunnel when Cloudflare SSH is down.
    $probeArgs = @('-o', 'BatchMode=yes', '-o', 'ConnectTimeout=15')
    if ($UseKey -and (Test-Path -LiteralPath $SshKeyPath)) {
      $probeArgs = @('-i', $SshKeyPath) + $probeArgs
    }
    $probeArgs += @($Target, 'true')
    & $sshExe @probeArgs *> $null
    return $LASTEXITCODE -eq 0
  } finally {
    $ErrorActionPreference = $previous
  }
}

function Start-Tunnel {
  param([string]$Target, [bool]$UseKey, [object[]]$ForwardSpecs)
  # Log via OpenSSH -E so we do not attach redirected handles that die with the
  # parent shell/job. Create the process through WMI so agent/tool Job Objects
  # do not kill the tunnel when the launcher session exits.
  $logPath = Join-Path $runRoot 'ssh.log'
  $argParts = @(
    '-N',
    '-o', 'ExitOnForwardFailure=yes',
    '-o', 'ServerAliveInterval=15',
    '-o', 'ServerAliveCountMax=6',
    '-o', 'TCPKeepAlive=yes',
    '-o', 'BatchMode=yes',
    '-o', 'ConnectTimeout=20',
    '-E', "`"$logPath`""
  )
  if ($UseKey) {
    $argParts = @('-i', "`"$SshKeyPath`"") + $argParts
  }
  foreach ($forward in $ForwardSpecs) {
    $argParts += @('-L', "127.0.0.1:$($forward.LocalPort):$($forward.DeviceIp):$($forward.RemotePort)")
  }
  $argParts += $Target

  $commandLine = @($sshExe) + $argParts -join ' '
  $created = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{
    CommandLine = $commandLine
    CurrentDirectory = $repoRoot
  }
  if ($null -eq $created -or [int]$created.ReturnValue -ne 0) {
    throw "Failed to create detached SSH tunnel process (ReturnValue=$($created.ReturnValue)). Command: $commandLine"
  }

  $processId = [int]$created.ProcessId
  $process = Get-Process -Id $processId -ErrorAction SilentlyContinue
  if (-not $process) {
    throw "SSH tunnel process $processId was created but is not running. See $logPath"
  }
  # Fake a process object shape used by the readiness loop.
  return $process
}

function Set-LocalApiTunnelEnv {
  param([string]$Value)
  $key = 'PROJECT_TRUTH_HIKVISION_TUNNEL_MAP'
  $lines = @()
  if (Test-Path -LiteralPath $apiRuntimeEnvPath) {
    $lines = @(Get-Content -LiteralPath $apiRuntimeEnvPath)
  } else {
    $lines = @(
      '# Auto-generated by scripts/ensure-bnpi-db-access.cjs.',
      '# Safe to delete; it will be regenerated on the next npm run dev.'
    )
  }

  $updated = $false
  $nextLines = foreach ($line in $lines) {
    if ($line -match "^$([regex]::Escape($key))=") {
      $updated = $true
      "$key=$Value"
    } else {
      $line
    }
  }
  if (-not $updated) {
    $nextLines += "$key=$Value"
  }
  Set-Content -LiteralPath $apiRuntimeEnvPath -Value $nextLines -Encoding UTF8
}

if ($StopExisting) {
  Stop-ExistingTunnel
  if ($PSBoundParameters.Count -eq 1) { return }
}

New-Item -ItemType Directory -Force -Path $runRoot | Out-Null

$forwardSpecs = @()
for ($i = 0; $i -lt $DeviceIps.Count; $i++) {
  $deviceIp = [string]$DeviceIps[$i]
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'http'
    LocalPort = $LocalHttpPortBase + $i
    RemotePort = 80
  }
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'https'
    LocalPort = $LocalHttpsPortBase + $i
    RemotePort = 443
  }
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'sdk'
    LocalPort = $LocalSdkPortBase + $i
    RemotePort = 8000
  }
}

$active = $null
if (Test-Path -LiteralPath $pidFile) {
  try {
    $record = Get-Content -Raw -LiteralPath $pidFile | ConvertFrom-Json
    $process = Get-Process -Id $record.ProcessId -ErrorAction SilentlyContinue
    $expectedLocalPorts = @($forwardSpecs | Select-Object -ExpandProperty LocalPort)
    $listeningCount = @($expectedLocalPorts | Where-Object { Test-TcpConnect 127.0.0.1 ([int]$_) }).Count
    if ($process -and $listeningCount -eq $expectedLocalPorts.Count) {
      $active = $record
    }
  } catch {
    $active = $null
  }
}

if (-not $active -and (Test-Path -LiteralPath $pidFile)) {
  Stop-ExistingTunnel
}

if (-not $active) {
  $target = $SshTarget
  $useKey = $false
  if (-not (Test-SshTarget -Target $target -UseKey:$false)) {
    if ($NoFallback) {
      throw "SSH target $target is not reachable. Confirm Cloudflare Access is logged in and ssh $target works."
    }
    $target = $FallbackSshTarget
    $useKey = $true
    if (-not (Test-SshTarget -Target $target -UseKey:$true)) {
      throw "Neither SSH target is reachable: primary=$SshTarget fallback=$FallbackSshTarget (fallback probed with -i $SshKeyPath). No tunnel process or active-state file was created."
    }
    Write-Host "Primary SSH $SshTarget unavailable; using LAN fallback $FallbackSshTarget with appliance key."
  }

  $process = Start-Tunnel -Target $target -UseKey $useKey -ForwardSpecs $forwardSpecs
  $expectedLocalPorts = @($forwardSpecs | Select-Object -ExpandProperty LocalPort)
  $readyDeadline = (Get-Date).AddSeconds(25)
  $listeningCount = 0
  do {
    Start-Sleep -Milliseconds 500
    $process.Refresh()
    if ($process.HasExited) { break }
    $listeningCount = @($expectedLocalPorts | Where-Object { Test-TcpConnect 127.0.0.1 ([int]$_) 500 }).Count
  } while ($listeningCount -ne $expectedLocalPorts.Count -and (Get-Date) -lt $readyDeadline)

  if ($process.HasExited -or $listeningCount -ne $expectedLocalPorts.Count) {
    $sshLogPath = Join-Path $runRoot 'ssh.log'
    $sshLog = Get-Content -Raw -LiteralPath $sshLogPath -ErrorAction SilentlyContinue
    if (-not $process.HasExited) {
      Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
    }
    Remove-Item -LiteralPath $pidFile -Force -ErrorAction SilentlyContinue
    throw "Hikvision remote device tunnel did not open all $($expectedLocalPorts.Count) verified ports (opened=$listeningCount). No active state was recorded. $sshLog"
  }

  $tunnelMap = (($forwardSpecs | ForEach-Object {
    "$($_.DeviceIp):$($_.RemotePort)=127.0.0.1:$($_.LocalPort)"
  }) -join ',')

  $active = [pscustomobject]@{
    GeneratedAt = (Get-Date).ToString('o')
    ProcessId = $process.Id
    SshTarget = $target
    DeviceIps = $DeviceIps
    Forwards = @($forwardSpecs | ForEach-Object {
      @{
        DeviceIp = $_.DeviceIp
        Name = $_.Name
        Local = "127.0.0.1:$($_.LocalPort)"
        Remote = "$($_.DeviceIp):$($_.RemotePort)"
      }
    })
    Env = "PROJECT_TRUTH_HIKVISION_TUNNEL_MAP=$tunnelMap"
    StopCommand = '.\scripts\start-hikvision-remote-device-tunnel.ps1 -StopExisting'
    Evidence = $runRoot
  }
  $active | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $pidFile -Encoding UTF8
  $active | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $runRoot 'tunnel.json') -Encoding UTF8
}

$envValue = ($active.Env -replace '^PROJECT_TRUTH_HIKVISION_TUNNEL_MAP=', '')
Set-LocalApiTunnelEnv -Value $envValue

$proof = foreach ($forward in @($active.Forwards)) {
  $localPort = [int](([string]$forward.Local -split ':')[-1])
  [pscustomobject]@{
    DeviceIp = $forward.DeviceIp
    Name = $forward.Name
    Local = $forward.Local
    Remote = $forward.Remote
    TcpOk = Test-TcpConnect 127.0.0.1 $localPort
  }
}

[pscustomobject]@{
  Status = if (($proof | Where-Object { -not $_.TcpOk }).Count -eq 0) { 'running' } else { 'degraded' }
  ProcessId = $active.ProcessId
  SshTarget = $active.SshTarget
  DeviceIps = $active.DeviceIps
  Env = $active.Env
  LocalApiEnvFile = $apiRuntimeEnvPath
  Proof = $proof
  Evidence = $active.Evidence
} | ConvertTo-Json -Depth 6
