param(
  [string[]]$DeviceIps = @('10.184.37.20', '10.184.37.21', '10.184.37.22'),
  [string]$SshTarget = 'project-truth-hris',
  [string]$FallbackSshTarget = 'infra@10.184.37.19',
  [string]$SshKeyPath = (Join-Path $env:USERPROFILE '.ssh\node-health-appliance_ed25519'),
  [int]$LocalHttpPortBase = 10080,
  [int]$LocalHttpsPortBase = 10443,
  [int]$LocalSdkPortBase = 18000,
  [switch]$StopExisting,
  [switch]$NoFallback
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$runtimeRoot = Join-Path $repoRoot '.runtime\hikvision-remote-device-tunnel'
$pidFile = Join-Path $runtimeRoot 'active.json'
$apiRuntimeEnvPath = Join-Path $repoRoot 'hris-api\.env.development.local'
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$runRoot = Join-Path $runtimeRoot "run-$stamp"
$sshExe = (Get-Command ssh.exe -ErrorAction Stop).Source

function Stop-ExistingTunnel {
  if (-not (Test-Path -LiteralPath $pidFile)) { return }
  $record = Get-Content -Raw -LiteralPath $pidFile | ConvertFrom-Json
  try {
    Stop-Process -Id $record.ProcessId -Force -ErrorAction Stop
    Write-Host "Stopped Hikvision remote device tunnel PID $($record.ProcessId)"
  } catch {
    Write-Host "Hikvision remote device tunnel PID $($record.ProcessId) is not running"
  }
  Remove-Item -LiteralPath $pidFile -Force -ErrorAction SilentlyContinue
}

function Test-TcpConnect {
  param([string]$HostName, [int]$Port, [int]$TimeoutMs = 1500)
  try {
    $client = [System.Net.Sockets.TcpClient]::new()
    $async = $client.BeginConnect($HostName, $Port, $null, $null)
    if (-not $async.AsyncWaitHandle.WaitOne($TimeoutMs, $false)) {
      $client.Close()
      return $false
    }
    $client.EndConnect($async)
    $client.Close()
    return $true
  } catch {
    return $false
  }
}

function Test-SshTarget {
  param([string]$Target)
  $previous = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  try {
    & $sshExe -o BatchMode=yes -o ConnectTimeout=15 $Target 'true' *> $null
    return $LASTEXITCODE -eq 0
  } finally {
    $ErrorActionPreference = $previous
  }
}

function Start-Tunnel {
  param([string]$Target, [bool]$UseKey, [object[]]$ForwardSpecs)
  $stdoutPath = Join-Path $runRoot 'ssh.stdout.log'
  $stderrPath = Join-Path $runRoot 'ssh.stderr.log'
  $args = @(
    '-N',
    '-o', 'ExitOnForwardFailure=yes',
    '-o', 'ServerAliveInterval=30',
    '-o', 'ServerAliveCountMax=3'
  )
  foreach ($forward in $ForwardSpecs) {
    $args += @('-L', "127.0.0.1:$($forward.LocalPort):$($forward.DeviceIp):$($forward.RemotePort)")
  }
  if ($UseKey) {
    $args = @('-i', $SshKeyPath) + $args
  }
  $args += $Target

  Start-Process -FilePath $sshExe `
    -ArgumentList $args `
    -RedirectStandardOutput $stdoutPath `
    -RedirectStandardError $stderrPath `
    -WindowStyle Hidden `
    -PassThru
}

function Set-LocalApiTunnelEnv {
  param([string]$Value)
  $key = 'PROJECT_TRUTH_HIKVISION_TUNNEL_MAP'
  $lines = @()
  if (Test-Path -LiteralPath $apiRuntimeEnvPath) {
    $lines = @(Get-Content -LiteralPath $apiRuntimeEnvPath)
  } else {
    $lines = @(
      '# Auto-generated by scripts/ensure-bnpi-db-access.cjs.',
      '# Safe to delete; it will be regenerated on the next npm run dev.'
    )
  }

  $updated = $false
  $nextLines = foreach ($line in $lines) {
    if ($line -match "^$([regex]::Escape($key))=") {
      $updated = $true
      "$key=$Value"
    } else {
      $line
    }
  }
  if (-not $updated) {
    $nextLines += "$key=$Value"
  }
  Set-Content -LiteralPath $apiRuntimeEnvPath -Value $nextLines -Encoding UTF8
}

if ($StopExisting) {
  Stop-ExistingTunnel
  if ($PSBoundParameters.Count -eq 1) { return }
}

New-Item -ItemType Directory -Force -Path $runRoot | Out-Null

$forwardSpecs = @()
for ($i = 0; $i -lt $DeviceIps.Count; $i++) {
  $deviceIp = [string]$DeviceIps[$i]
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'http'
    LocalPort = $LocalHttpPortBase + $i
    RemotePort = 80
  }
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'https'
    LocalPort = $LocalHttpsPortBase + $i
    RemotePort = 443
  }
  $forwardSpecs += [pscustomobject]@{
    DeviceIp = $deviceIp
    Name = 'sdk'
    LocalPort = $LocalSdkPortBase + $i
    RemotePort = 8000
  }
}

$active = $null
if (Test-Path -LiteralPath $pidFile) {
  try {
    $record = Get-Content -Raw -LiteralPath $pidFile | ConvertFrom-Json
    $process = Get-Process -Id $record.ProcessId -ErrorAction SilentlyContinue
    $expectedLocalPorts = @($forwardSpecs | Select-Object -ExpandProperty LocalPort)
    $listeningCount = @($expectedLocalPorts | Where-Object { Test-TcpConnect 127.0.0.1 ([int]$_) }).Count
    if ($process -and $listeningCount -eq $expectedLocalPorts.Count) {
      $active = $record
    }
  } catch {
    $active = $null
  }
}

if (-not $active -and (Test-Path -LiteralPath $pidFile)) {
  Stop-ExistingTunnel
}

if (-not $active) {
  $target = $SshTarget
  $useKey = $false
  if (-not (Test-SshTarget -Target $target)) {
    if ($NoFallback) {
      throw "SSH target $target is not reachable. Confirm Cloudflare Access is logged in and ssh $target works."
    }
    $target = $FallbackSshTarget
    $useKey = $true
  }

  $process = Start-Tunnel -Target $target -UseKey $useKey -ForwardSpecs $forwardSpecs
  Start-Sleep -Seconds 3
  if ($process.HasExited) {
    $stderrPath = Join-Path $runRoot 'ssh.stderr.log'
    $stderr = Get-Content -Raw -LiteralPath $stderrPath -ErrorAction SilentlyContinue
    throw "Hikvision remote device tunnel exited immediately. $stderr"
  }

  $active = [pscustomobject]@{
    GeneratedAt = (Get-Date).ToString('o')
    ProcessId = $process.Id
    SshTarget = $target
    DeviceIps = $DeviceIps
    Forwards = @($forwardSpecs | ForEach-Object {
      @{
        DeviceIp = $_.DeviceIp
        Name = $_.Name
        Local = "127.0.0.1:$($_.LocalPort)"
        Remote = "$($_.DeviceIp):$($_.RemotePort)"
      }
    })
    Env = "PROJECT_TRUTH_HIKVISION_TUNNEL_MAP=$(($forwardSpecs | ForEach-Object { "$($_.DeviceIp):$($_.RemotePort)=127.0.0.1:$($_.LocalPort)" }) -join ',')"
    StopCommand = '.\scripts\start-hikvision-remote-device-tunnel.ps1 -StopExisting'
    Evidence = $runRoot
  }
  $active | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $pidFile -Encoding UTF8
  $active | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $runRoot 'tunnel.json') -Encoding UTF8
}

$envValue = ($active.Env -replace '^PROJECT_TRUTH_HIKVISION_TUNNEL_MAP=', '')
Set-LocalApiTunnelEnv -Value $envValue

$proof = foreach ($forward in @($active.Forwards)) {
  $localPort = [int](([string]$forward.Local -split ':')[-1])
  [pscustomobject]@{
    DeviceIp = $forward.DeviceIp
    Name = $forward.Name
    Local = $forward.Local
    Remote = $forward.Remote
    TcpOk = Test-TcpConnect 127.0.0.1 $localPort
  }
}

[pscustomobject]@{
  Status = if (($proof | Where-Object { -not $_.TcpOk }).Count -eq 0) { 'running' } else { 'degraded' }
  ProcessId = $active.ProcessId
  SshTarget = $active.SshTarget
  DeviceIps = $active.DeviceIps
  Env = $active.Env
  LocalApiEnvFile = $apiRuntimeEnvPath
  Proof = $proof
  Evidence = $active.Evidence
} | ConvertTo-Json -Depth 6
