import { z } from "zod";
import { isValidEntityId as isValidObjectId } from "../helper/id-validation.helper";


// Timesheetline Schema (full, including ID)
export const TimesheetlineSchema = z.object({
	id: z.string().refine((val) => isValidObjectId(val)),
	organizationId: z.string().min(1),
	employeeId: z.string().refine((val) => isValidObjectId(val)),
	timesheetId: z.string().refine((val) => isValidObjectId(val)),
	payrollPeriodId: z.string().refine((val) => isValidObjectId(val)),
	attendanceId: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	date: z.coerce.date(),
	timeIn: z.coerce.date().nullable().optional(),
	timeBreak: z.coerce.date().nullable().optional(),
	timeOut: z.coerce.date().nullable().optional(),
	status: z.string().default("NOT_CLOCKED_IN"),
	behaviorFlags: z.array(z.string()).default([]),
	scheduleSnapshot: z.any().nullable().optional(),
	hoursWorked: z.string().nullable().optional(),
	regularHours: z.string().nullable().optional(),
	overtimeHours: z.string().nullable().optional(),
	undertimeHours: z.string().nullable().optional(),
	lateHours: z.string().nullable().optional(),
	earlyOutHours: z.string().nullable().optional(),
	breakMinutes: z.number().int().nullable().optional(),
	employeeNotes: z.string().nullable().optional(),
	approverNotes: z.string().nullable().optional(),
	notes: z.string().nullable().optional(),
	metadata: z.any().nullable().optional(),
	primaryMarker: z.string().nullable().optional(),
	isManualEntry: z.boolean().default(false),
	isVirtual: z.boolean().default(false),
	revisionNo: z.number().int().default(1),
	isEffective: z.boolean().default(true),
	ledgerType: z.string().default("SNAPSHOT"),
	supersedesLineId: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	supersededById: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	supersededAt: z.coerce.date().nullable().optional(),
	editedAt: z.coerce.date().nullable().optional(),
	editedBy: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	editReason: z.string().nullable().optional(),
	employeeCodeSnapshot: z.string().nullable().optional(),
	employeeNameSnapshot: z.string().nullable().optional(),
	departmentIdSnapshot: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	departmentNameSnapshot: z.string().nullable().optional(),
	reportToIdSnapshot: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	workforceSourceSnapshot: z.string().nullable().optional(),
	agencyIdSnapshot: z.string().refine((val) => isValidObjectId(val)).nullable().optional(),
	dayLaborType: z.enum(["DIRECT", "INDIRECT"]).nullable().optional(),
	projectCode: z.string().max(64).nullable().optional(),
	isDeleted: z.boolean(),
	createdAt: z.coerce.date(),
	updatedAt: z.coerce.date(),
});

export type Timesheetline = z.infer<typeof TimesheetlineSchema>;

// Create Timesheetline Schema (excluding ID, createdAt, updatedAt, and computed fields)
export const CreateTimesheetlineSchema = TimesheetlineSchema.omit({
	id: true,
	createdAt: true,
	updatedAt: true,
}).partial({
	attendanceId: true,
	timeIn: true,
	timeBreak: true,
	timeOut: true,
	status: true,
	behaviorFlags: true,
	scheduleSnapshot: true,
	hoursWorked: true,
	regularHours: true,
	overtimeHours: true,
	undertimeHours: true,
	lateHours: true,
	earlyOutHours: true,
	breakMinutes: true,
	employeeNotes: true,
	approverNotes: true,
	notes: true,
	metadata: true,
	primaryMarker: true,
	isManualEntry: true,
	isVirtual: true,
	revisionNo: true,
	isEffective: true,
	ledgerType: true,
	supersedesLineId: true,
	supersededById: true,
	supersededAt: true,
	editedAt: true,
	editedBy: true,
	editReason: true,
	employeeCodeSnapshot: true,
	employeeNameSnapshot: true,
	departmentIdSnapshot: true,
	departmentNameSnapshot: true,
	reportToIdSnapshot: true,
	workforceSourceSnapshot: true,
	agencyIdSnapshot: true,
	dayLaborType: true,
	projectCode: true,
	isDeleted: true,
});

export type CreateTimesheetline = z.infer<typeof CreateTimesheetlineSchema>;

// Update Timesheetline Schema (partial, excluding immutable fields and relations)
export const UpdateTimesheetlineSchema = TimesheetlineSchema.omit({
	id: true,
	createdAt: true,
	updatedAt: true,
}).partial();

export type UpdateTimesheetline = z.infer<typeof UpdateTimesheetlineSchema>;
