apiVersion: apps/v1
kind: Deployment
metadata:
  name: hris-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: HIKVISION_AUTHORIZED_CARD_CANARY_DEVICE_ID
              value: cmripjwkw00ffl0013lfxcbxw
            - name: HIKVISION_AUTHORIZED_FACE_CANARY_DEVICE_ID
              value: cmpxw13hx002h7zwso7dyedrn
            - name: HIKVISION_FDLIB_FACE_DELIVERY_ORIGIN
              value: http://10.184.37.19:3101
