namespace: dev

resources:
  - priority-classes.yaml
  - runtime.yaml

patches:
  - path: hris-api-credential-recovery-env.patch.yaml

images:
  - name: hris-api-db-init
    newTag: develop
  - name: hris-api-local
    newTag: develop
  - name: hris-app-local
    newTag: develop
  - name: hris-emp-app-local
    newTag: develop
  - name: hris-callback-outbox
    newTag: develop
